"""What every page is rendered from: the assertions, re-read from disk on each call, and the prose helpers that weave authored blocks and counts into the pages rendered from them.

`ASKED` is filled as `authored()` and `woven()` run, and the gate reads it back
after a render (solorepo's DR-144, solorepo's DR-152).
"""
import ast
import posixpath
import re
from typing import Any

import yaml

from lib.render import META

# An entry *is* its assertion file. Two spellings of the same path: one from the
# repository root, one from `.meta/`, where `decisions.md` sits.
RECORD = ".meta/assertions/decisions/DR-{}.yaml"
ENTRY = "assertions/decisions/DR-{}.yaml"


BANNER = ("<!-- Generated by .meta/render.py from {src}. Do not edit by hand:\n"
          "     edit the assertions and re-render. -->\n\n")


NO_SLOT = "no Artifact asserts a {slot} for {rel}, which {target} is rendered from"
"""What filling an authored slot raises where no Artifact asserts that slot for the file."""

NO_PRECHECK = ("no module in .meta/checks/ registers a step with `@check(..., pre=True)`, "
               "and a count cited in prose is derived from those that are")
"""What deriving a count raises where nothing in `.meta/checks/` registers a pre-check."""

NO_COUNT = "prose cites a count of {name}, which nothing derives; the counts are {known}"
"""What filling a `{#name}` citation raises where nothing derives that count."""

NO_BLOCK = "{where} asserts no woven block named {block!r}"
"""What weaving a block raises where the assertions hold no block of that name."""


# Every block of authored prose a render asked for, as `(host, slot, block)`,
# filled as `authored()` and `woven()` are called. `host` is the Artifact's
# path or the Discipline's id, and `block` is the woven block's name — empty
# where the slot is the whole block. The gate holds this against where the
# prose is asserted, in both directions: prose asserted in the file
# Specialization replaces, and prose asserted that nothing asks for. A set read
# from a run is the set, because a list typed beside the call sites would be
# the second copy all of this exists to remove (solorepo's DR-144, DR-152).
ASKED: set[tuple[str, str, str]] = set()


def load(rel: str) -> Any | None:
    """Parses one assertion file, or answers None where it is absent.

    Missing is a legitimate answer: a portfolio has no scaffold-only
    assertions, so a renderer asking for them gets nothing rather than a crash.

    Args:
        rel: The file's path relative to `.meta/`.

    Returns:
        The parsed YAML document, re-read from disk on every call, or None
        when no file is at that path.
    """
    path = META / rel
    return yaml.safe_load(path.read_text()) if path.exists() else None


def record() -> list[dict[str, Any]]:
    """Every Decision, newest last, from one file per entry.

    One entry is one file so that adding or editing one costs that file rather
    than the whole record. `check.py` needs no change for it — its collector
    already walks `assertions/` — and the numbering is the sort, so the directory
    listing is the order.
    """
    rows: list[dict[str, Any]] = []
    for path in sorted((META / "assertions" / "decisions").glob("DR-*.yaml")):
        rows += (yaml.safe_load(path.read_text()) or {}).get("decisions") or []
    return rows


def all_artifacts() -> list[dict[str, Any]]:
    """Every Artifact asserted, inherited and the portfolio's own.

    Two files for the same reason the Disciplines and the Vocabulary have two:
    `assertions/imported/` is what Specialization copies, and
    `assertions/structure.yaml` is the portfolio's own and never synced. The
    pages a portfolio renders are the scaffold's, so the Artifacts carrying
    their prose are inherited; `SPECIALIZE.md`'s is not, because a portfolio
    has no such page.
    """
    return [a for rel in ("assertions/imported/structure.yaml", "assertions/structure.yaml")
            for a in (load(rel) or {}).get("artifacts") or []]


def artifacts() -> dict[str, str]:
    """Artifact id -> path, from the assertions."""
    return {a["id"]: a["path"] for a in all_artifacts()}


def authored(target: str, slot: str = "preamble") -> str:
    """The prose a generated page opens or closes with, from its Artifact.

    `render.py` writes pages and does not author them: a generator carrying
    prose of its own is a second author, and the drift it was built to prevent
    (solorepo's DR-144). `target` is the path as `TARGETS` names it, relative
    to `.meta/`, which is the same path the Artifact asserts.

    Missing is an error and not an empty page. A `None` spliced into the list
    this returns into arrives as `sequence item 1: expected str` several frames
    away, which is the shape A7 says a step does not print; named here, a
    renamed `path` or a dropped slot says which page and which slot.
    """
    rel = posixpath.normpath(posixpath.join(".meta", target))
    ASKED.add((rel, slot, ""))
    for a in all_artifacts():
        if a["path"] == rel and a.get(slot):
            return str(a[slot]).strip() + "\n"
    raise LookupError(NO_SLOT.format(slot=slot, rel=rel, target=target))


# A count about the record, cited in prose as `{#name}` and filled by the
# render. A number an author typed is true the day it is typed and silently
# false one landing later: step two of Specialization said "three of
# `check.py`'s four prechecks load the channel or a hook" across the two
# landings that added a fifth precheck and a sixth, and that sentence is the
# reason the procedure gives for copying the channel into a portfolio
# (solorepo's #231). Filled here it is held by `rendered prose`, which compares
# the committed page against a fresh render: the count moves, the page is
# stale, the gate says so — so the arithmetic is the render's and no step of
# the gate is added to hold it (solorepo's DR-154).
COUNT = re.compile(r"\{#(?P<name>[a-z][a-z ]*[a-z])\}")


# Small counts as the words a sentence wants. The number is filled into the
# middle of a sentence somebody wrote, where a numeral reads as a citation
# rather than as a quantity; past twelve the word is the harder read and the
# digits win.
NUMBERS = ("no", "one", "two", "three", "four", "five", "six", "seven", "eight",
           "nine", "ten", "eleven", "twelve")


def prechecks() -> list[str]:
    """The gate's prechecks, by function name, read out of the modules that
    register them.

    Read and not imported. The renderer has one dependency — `uvx --python 3.13
    --with pyyaml python .meta/render.py` is how it is run, and how `check.py`
    runs it — and the modules a count of the gate's steps reaches into have
    LinkML. Each step registers itself at its definition, so
    `@check(..., pre=True)` is the declaration, and `ast` reads it without
    running anything.

    The steps live in `.meta/checks/`, one module per subject
    (solorepo's DR-150), and the probes one level further down in
    `.meta/checks/probes/`, one module per subject under test (solorepo's DR-209),
    so the whole tree is read rather than one file: which module a precheck is
    written in is those splits' business, and a count of them should not move
    when one is carried from one subject to another.

    Empty is an error and not a count of none. A rewrite that registers steps
    some other way says so here, rather than leaving the prose that cites this
    to assert there are no prechecks at all.
    """
    found: list[str] = []
    for path in sorted((META / "checks").rglob("*.py")):
        for node in ast.parse(path.read_text()).body:
            for decorator in getattr(node, "decorator_list", []):
                if not (isinstance(decorator, ast.Call)
                        and getattr(decorator.func, "id", None) == "check"):
                    continue
                if (any(word.arg == "pre" and getattr(word.value, "value", None) is True
                        for word in decorator.keywords)
                        and isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))):
                    found.append(node.name)
    if not found:
        raise LookupError(NO_PRECHECK)
    return found


def counts() -> dict[str, int]:
    """What prose may cite a count of, each derived from the thing counted."""
    return {"prechecks": len(prechecks())}


def counted(text: str) -> str:
    """Every count the prose of a page cites, filled.

    Applied to the finished page rather than to each scalar as it is read, so
    that a count can be cited from any prose the assertions hold and no
    generator has to remember to ask for it.

    A name nothing derives is an error and not a number invented, for the
    reason `authored()` gives: an unfilled `{#...}` reaching a page is the
    drift this exists to remove, printed.
    """
    table = counts()

    def fill(m: re.Match[str]) -> str:
        if m["name"] not in table:
            raise LookupError(NO_COUNT.format(name=m["name"], known=", ".join(sorted(table))))
        n = table[m["name"]]
        return NUMBERS[n] if n < len(NUMBERS) else str(n)

    return COUNT.sub(fill, text)


def woven(host: str | dict[str, Any], block: str, **holes: Any) -> str:
    """A named block of the prose a generator writes *between* what it derives.

    `preamble` and `postamble` are identified by where they sit; a block in the
    middle of a page is not, so it carries a name and is asked for by it
    (solorepo's DR-152). A block hangs off what it frames, which is what `host`
    says: a page's path, as `TARGETS` spells it, where the block belongs to that
    one Artifact; a Discipline, where every reading compiled from it carries the
    same block and one copy per page would be the second copy.

    `holes` fills the block's named holes — `{role}` — and filling one is the
    whole of what a generator may add to prose it is handed. A block with no
    holes is never formatted, so a stray brace in the prose is prose.

    Missing is an error naming the host and the block, for the reason
    `authored()` gives: a dropped block arrives frames away from its cause.
    """
    if isinstance(host, str):
        rel = posixpath.normpath(posixpath.join(".meta", host))
        ASKED.add((rel, "woven", block))
        where = rel
        host = next((a for a in all_artifacts()
                     if a["path"] == rel and any(p.get("name") == block for p in a.get("woven") or [])), {})
    else:
        where = host["id"]
        ASKED.add((where, "woven", block))
    for prose in host.get("woven") or []:
        if prose["name"] == block:
            text = str(prose["text"]).strip()
            return str(text.format(**holes)) if holes else text
    raise LookupError(NO_BLOCK.format(where=where, block=block))


def accounted_by(target: str) -> str:
    """The DRs naming this page under `enacted_in`, as A20's back-pointer.

    Rendered rather than typed, so `enacted_in` stays the only statement of the
    link. Hand-written artifacts cite the number in prose instead, which is what
    `check.py` holds them to.

    `target` is the path as `TARGETS` names it, relative to `.meta/`.
    """
    rel = posixpath.normpath(posixpath.join(".meta", target))
    rows = record()
    paths = artifacts()
    here = posixpath.dirname(rel)
    cited = [d for d in rows
             if rel in [paths.get(a, a) for a in (d.get("enacted_in") or [])]]
    if not cited:
        return ""
    links = ", ".join(
        f"[DR-{d['id'].rsplit('/', 1)[-1]}]"
        f"({posixpath.relpath(RECORD.format(d['id'].rsplit('/', 1)[-1]), here)})"
        for d in cited)
    return "\n---\n\n**Where this came from.** " + links + "\n"
