"""The four rendered skills, and the line sets some of them share.

PR First's two are compiled from the Discipline through `skill()`, one for the
coder Role and one for the reviewer (solorepo's DR-060). `wikisplain` and
`technical-writing` are authored skills read from the structure assertions
through `authored_skill()` (solorepo's DR-144). `READING` and `BODY` reach
the two PR First skills; `DEREFERENCE` is the coder's alone.
"""
import textwrap
from collections.abc import Sequence
from typing import Any, cast

from lib.render import pages, record


def _discipline(name: str) -> dict[str, Any] | None:
    for rel in ("assertions/disciplines.yaml", "assertions/imported/disciplines.yaml"):
        for d in (record.load(rel) or {}).get("disciplines") or []:
            if d["name"] == name:
                return cast(dict[str, Any], d)
    return None


def channel() -> dict[str, Any] | None:
    """The channel's verbs, once: `.meta/say/verbs.yaml`."""
    return cast(dict[str, Any] | None, record.load("say/verbs.yaml"))


def verb_line(program: dict[str, Any], verb: dict[str, Any], role: str | None = None) -> str:
    """How a verb is typed, from the table: the program, `--role` for any Role
    but the channel's default, the verb unless the program is the verb, and
    the shape of its arguments."""
    words = [f".meta/say/{program['name']}"]
    if role and role != "coder":
        words.append(f"--role {role}")
    if verb["name"] != program["name"]:
        words.append(verb["name"])
    if verb.get("usage"):
        words.append(verb["usage"])
    return " ".join(words)


def skill(name: str, discipline: str, commands: Sequence[str],
          forms: Sequence[tuple[str, str, str]] = (), role: str | None = None) -> str | None:
    """A Discipline, compiled for this harness, and for one Role (solorepo's DR-117).

    A skill is a Discipline plus the commands that carry it out, in the shape one
    harness loads on demand. Everything here is read from the assertions — the
    steps, the judgement, the Articles that enforce it, and any form's own fence.
    Nothing is restated, because a skill that restated the Discipline would be
    the copy nothing checks, and the one an agent actually reads.

    With a Role, the mechanical steps are one line and the Role's verbs, read
    from `verbs.yaml`: the verbs are the steps, each refuses its own misuse,
    and a reading names no verb its Role does not hold. The steps the assertion
    keeps are the ones no verb enforces. Without a Role the reading is the
    whole Discipline's, which is `disciplines.md`'s.

    The paragraphs between those parts are the Discipline's `woven` blocks and
    not this function's (solorepo's DR-152). They hang off the Discipline rather
    than off either page, because one Discipline compiles into a reading per
    Role: asserted on the Artifact each is written to, every one of them would
    be a copy of the last. `{role}` is the only thing a reading adds to one.

    Only the Claude Code target is emitted. The frontmatter an APM primitive
    wants is still unverified (solorepo's DR-040), and writing plausible field names would
    be worse than the gap; this is the same compilation at the scale that can be
    tested today.
    """
    d = _discipline(discipline)
    if d is None:
        return None
    charter = record.load("assertions/imported/charter.yaml") or {}
    articles = [a for a in charter.get("articles") or [] if a.get("enforces") == d["id"]]
    out = ["---", f"name: {name}", "description: >-"]
    target = f"../.claude/skills/{name}/SKILL.md"
    out += ["  " + line for line in textwrap.wrap(record.authored(target, "description"), 76)]
    out += ["---\n",
            "<!-- Generated by .meta/render.py from assertions/imported/disciplines.yaml.",
            "     Do not edit by hand: edit the assertion and re-render. -->\n",
            f"# {d['name']}\n",
            d["description"].strip() + "\n",
            "## Steps\n"]
    if role:
        table = channel() or {"programs": []}
        out += [record.woven(d, "verbs", role=role) + "\n"]
        for program in table["programs"]:
            held = [v for v in program["verbs"] if role in v["held_by"]]
            out += [f"- `{verb_line(program, v, role)}` — {v['does']}" for v in held]
        out += ["", record.woven(d, "steps") + "\n"]
    step_lines = [
        f"{i}. **{s['name'].rstrip('.')}.** {s['statement'].strip()}"
        for i, s in enumerate(d["steps"], 1)
    ]
    out += ["\n".join(step_lines) + "\n",
            "## Where the judgement is\n",
            d["judgement"].strip() + "\n",
            record.woven(d, "commands") + "\n",
            "## Commands\n", "```bash", *commands, "```\n"]
    for title, form_name, block in forms:
        out += [f"## {title}\n", record.woven(d, block) + "\n", "```markdown",
                pages.form(form_name).rstrip("\n"), "```\n"]
    if articles:
        out.append("## What is checked\n")
        for a in articles:
            out.append(f"- **A{a['id'].rsplit('/', 1)[-1]}.** {a['statement'].strip()}")
        out.append("")
    return "\n".join(out)


READING = ["just sweep                                # what this branch owns, and what it owes",
           "just pr <n> --threads                     # the threads: owed, held, answered; and each verdict with its head",
           "just pr <n>                               # the gate: A15 and A16",
           "#   Watching the pull request, and removing what a merge leaves behind, are the",
           "#   harness's business, not yours: AGENTS.md says how this one does both."]


# The coder's alone, and only in the coder's reading of the Discipline: the
# reading of a citation is run by whoever wrote it, before the hand-off, and a
# reviewer who reaches for it is doing the work over (solorepo's DR-134).
DEREFERENCE = [
    "just dereference                          # the citations this branch wrote, read against what they name",
    "#   Not a gate: its `x` is a finding to answer, and it blocks no merge."]


# The heading, the form's own file, and the name of the Discipline's `woven`
# block that introduces it. Naming a block is plumbing; writing one is not.
BODY = [("The body", "pull-request.md", "the body")]


def pr_first_skill() -> str | None:
    """The coder's reading. `/pr-first` and not `/pr-first-coder`, because the
    coder is the channel's default Role too: a session that names no Role is
    the coder's, in what it types and in what it reads (solorepo's DR-117)."""
    return skill(
        "pr-first", "PR First", READING + DEREFERENCE, BODY, role="coder")


def pr_first_reviewer_skill() -> str | None:
    """The reviewer's reading: its verbs, the form a pull request is held to,
    and the judgement a reviewer's point is owed (solorepo's DR-117)."""
    return skill(
        "pr-first-reviewer", "PR First", READING, BODY, role="reviewer")


def authored_skill(name: str) -> str:
    """Renders an operational skill from the `description` and `preamble` slots
    its Artifact asserts (solorepo's DR-144)."""
    target = f"../.claude/skills/{name}/SKILL.md"
    desc = record.authored(target, "description").strip()
    body = record.authored(target).strip()
    return "\n".join([
        "---",
        f"name: {name}",
        "description: >-",
        *["  " + line for line in textwrap.wrap(desc, 76)],
        "---",
        "",
        "<!-- Generated by .meta/render.py from assertions/imported/structure.yaml.",
        "     Do not edit by hand: edit the assertion and re-render. -->",
        "",
        body,
        "",
    ])


def wikisplain_skill() -> str:
    """Operational authoring skill for Knowledge Management wiki concepts (solorepo's DR-187)."""
    return authored_skill("wikisplain")


def technical_writing_skill() -> str:
    """Technical writing skill fusing Diátaxis, Google style, and Literate
    Programming (solorepo's DR-171, solorepo's DR-175, solorepo's DR-176,
    solorepo's DR-187, solorepo's DR-194, solorepo's DR-196), and the rubric
    governing source bodies (solorepo's DR-207)."""
    return authored_skill("technical-writing")
