"""The three rendered skills: `wikisplain`, `search` and `technical-writing`.

Each is an authored skill read from the structure assertions through
`authored_skill()` (stereorepo's DR-144).
"""
import textwrap

from lib.render import record

NBSP = "\u00a0"
"""Holds a possessive to the number it cites while a description is wrapped, so
`stereorepo's DR-nnn` never breaks across lines, where no citation check reads it."""


def authored_skill(name: str) -> str:
    """Renders an operational skill from the `description` and `preamble` slots
    its Artifact asserts (stereorepo's DR-144)."""
    target = f"../.claude/skills/{name}/SKILL.md"
    desc = record.authored(target, "description").strip()
    body = record.authored(target).strip()
    return "\n".join([
        "---",
        f"name: {name}",
        "description: >-",
        *["  " + line.replace(NBSP, " ")
          for line in textwrap.wrap(desc.replace("'s DR-", f"'s{NBSP}DR-"), 76)],
        "---",
        "",
        "<!-- Generated by .meta/render.py from assertions/imported/structure.yaml.",
        "     Do not edit by hand: edit the assertion and re-render. -->",
        "",
        body,
        "",
    ])


def wikisplain_skill() -> str:
    """Operational authoring skill for Knowledge Management wiki concepts (stereorepo's DR-187)."""
    return authored_skill("wikisplain")


def search_skill() -> str:
    """Operational retrieval skill querying assertions and wiki concepts off the
    root verb surface (stereorepo's DR-103, stereorepo's DR-337, stereorepo's DR-349)."""
    return authored_skill("search")


def technical_writing_skill() -> str:
    """Technical writing skill fusing Diátaxis, Google style, and Literate
    Programming (stereorepo's DR-171, stereorepo's DR-334,
    stereorepo's DR-187, stereorepo's DR-337, stereorepo's DR-196), and the rubric
    governing source bodies (stereorepo's DR-207)."""
    return authored_skill("technical-writing")
