"""The four rendered skills, and the line sets some of them share.

PR First's two are compiled from the Discipline through `skill()`, one for the
coder Role and one for the reviewer (solorepo's DR-060). `wikisplain` and
`technical-writing` are written out here, with only their description read
from the assertions. `READING` and `BODY` reach the two PR First skills;
`DEREFERENCE` is the coder's alone.
"""
import textwrap

from lib.render import pages, record


def _discipline(name):
    for rel in ("assertions/disciplines.yaml", "assertions/imported/disciplines.yaml"):
        for d in (record.load(rel) or {}).get("disciplines") or []:
            if d["name"] == name:
                return d
    return None


def channel():
    """The channel's verbs, once: `.meta/say/verbs.yaml`."""
    return record.load("say/verbs.yaml")


def verb_line(program, verb, role=None):
    """How a verb is typed, from the table: the program, `--role` for any Role
    but the channel's default, the verb unless the program is the verb, and
    the shape of its arguments."""
    words = [f".meta/say/{program['name']}"]
    if role and role != "coder":
        words.append(f"--role {role}")
    if verb["name"] != program["name"]:
        words.append(verb["name"])
    if verb.get("usage"):
        words.append(verb["usage"])
    return " ".join(words)


def skill(name, discipline, commands, forms=(), role=None):
    """A Discipline, compiled for this harness, and for one Role (solorepo's DR-117).

    A skill is a Discipline plus the commands that carry it out, in the shape one
    harness loads on demand. Everything here is read from the assertions — the
    steps, the judgement, the Articles that enforce it, and any form's own fence.
    Nothing is restated, because a skill that restated the Discipline would be
    the copy nothing checks, and the one an agent actually reads.

    With a Role, the mechanical steps are one line and the Role's verbs, read
    from `verbs.yaml`: the verbs are the steps, each refuses its own misuse,
    and a reading names no verb its Role does not hold. The steps the assertion
    keeps are the ones no verb enforces. Without a Role the reading is the
    whole Discipline's, which is `disciplines.md`'s.

    The paragraphs between those parts are the Discipline's `woven` blocks and
    not this function's (solorepo's DR-152). They hang off the Discipline rather
    than off either page, because one Discipline compiles into a reading per
    Role: asserted on the Artifact each is written to, every one of them would
    be a copy of the last. `{role}` is the only thing a reading adds to one.

    Only the Claude Code target is emitted. The frontmatter an APM primitive
    wants is still unverified (solorepo's DR-040), and writing plausible field names would
    be worse than the gap; this is the same compilation at the scale that can be
    tested today.
    """
    d = _discipline(discipline)
    if d is None:
        return None
    articles = [a for a in ((record.load("assertions/imported/charter.yaml") or {}).get("articles") or [])
                if a.get("enforces") == d["id"]]
    out = ["---", f"name: {name}", "description: >-"]
    target = f"../.claude/skills/{name}/SKILL.md"
    out += ["  " + line for line in textwrap.wrap(record.authored(target, "description"), 76)]
    out += ["---\n",
            "<!-- Generated by .meta/render.py from assertions/imported/disciplines.yaml.",
            "     Do not edit by hand: edit the assertion and re-render. -->\n",
            f"# {d['name']}\n",
            d["description"].strip() + "\n",
            "## Steps\n"]
    if role:
        table = channel() or {"programs": []}
        out += [record.woven(d, "verbs", role=role) + "\n"]
        for program in table["programs"]:
            held = [v for v in program["verbs"] if role in v["held_by"]]
            out += [f"- `{verb_line(program, v, role)}` — {v['does']}" for v in held]
        out += ["", record.woven(d, "steps") + "\n"]
    out += ["\n".join(f"{i}. {s.strip()}" for i, s in enumerate(d["steps"], 1)) + "\n",
            "## Where the judgement is\n",
            d["judgement"].strip() + "\n",
            record.woven(d, "commands") + "\n",
            "## Commands\n", "```bash", *commands, "```\n"]
    for title, form_name, block in forms:
        out += [f"## {title}\n", record.woven(d, block) + "\n", "```markdown",
                pages.form(form_name).rstrip("\n"), "```\n"]
    if articles:
        out.append("## What is checked\n")
        for a in articles:
            out.append(f"- **A{a['id'].rsplit('/', 1)[-1]}.** {a['statement'].strip()}")
        out.append("")
    return "\n".join(out)


READING = ["python3 .meta/check_pr.py --sweep          # what this branch owns, and what it owes",
           "python3 .meta/check_pr.py <n> --threads    # the threads: owed, held, answered; and each verdict with its head",
           "python3 .meta/check_pr.py <n>              # the gate: A15 and A16",
           "#   Watching the pull request, and removing what a merge leaves behind, are the",
           "#   harness's business, not yours: AGENTS.md says how this one does both."]


# The coder's alone, and only in the coder's reading of the Discipline: the
# reading of a citation is run by whoever wrote it, before the hand-off, and a
# reviewer who reaches for it is doing the work over (solorepo's DR-134).
DEREFERENCE = [
    "just dereference                          # the citations this branch wrote, read against what they name",
    "#   Not a gate: its `x` is a finding to answer, and it blocks no merge."]


# The heading, the form's own file, and the name of the Discipline's `woven`
# block that introduces it. Naming a block is plumbing; writing one is not.
BODY = [("The body", "pull-request.md", "the body")]


def pr_first_skill():
    """The coder's reading. `/pr-first` and not `/pr-first-coder`, because the
    coder is the channel's default Role too: a session that names no Role is
    the coder's, in what it types and in what it reads (solorepo's DR-117)."""
    return skill(
        "pr-first", "PR First", READING + DEREFERENCE, BODY, role="coder")


def pr_first_reviewer_skill():
    """The reviewer's reading: its verbs, the form a pull request is held to,
    and the judgement a reviewer's point is owed (solorepo's DR-117)."""
    return skill(
        "pr-first-reviewer", "PR First", READING, BODY, role="reviewer")


def wikisplain_skill():
    """Operational authoring skill for Knowledge Management wiki concepts (solorepo's DR-187)."""
    desc = record.authored("../.claude/skills/wikisplain/SKILL.md", "description").strip()
    return "\n".join([
        "---",
        "name: wikisplain",
        "description: >-",
        *["  " + line for line in textwrap.wrap(desc, 76)],
        "---",
        "",
        "<!-- Generated by .meta/render.py from assertions/structure.yaml.",
        "     Do not edit by hand: edit the assertion and re-render. -->",
        "",
        "# /wikisplain",
        "",
        "The `/wikisplain` skill creates, explains, and verifies encyclopedic wiki pages in `wiki/<context>/` following the [[knowledge-management|Knowledge Management]] discipline and Wikipedia editorial conventions (solorepo's DR-187).",
        "",
        "## When to Use",
        "",
        "- Minting a new concept in the Ubiquitous Language that requires maintainer-facing exposition.",
        "- Explaining an architectural subsystem, component, or domain concept for new maintainers.",
        "- Scaffolding a canonical wiki page with compliant MOS:LEAD phrasing, frontmatter, and closed-world wikilinks.",
        "- Checking for semantic duplicates or collisions against existing vocabulary and wiki pages.",
        "",
        "## Verbs",
        "",
        "- `just wikisplain <concept> [--context <context>] [--definition <def>] [--synonyms <s1,s2>]` — scaffold a wiki page and verify compliance",
        "- `python3 .meta/wikisplain.py <concept> --dry-run` — preview page content without writing to disk",
        "- `python3 .meta/wikisplain.py <concept> --check-duplicate` — check if a concept or slug already exists",
        "",
        "## Instructions",
        "",
        "1. **Check for Duplicates:** Run `python3 .meta/wikisplain.py \"<Concept>\" --check-duplicate` to verify no collision exists in vocabulary or existing wiki files.",
        "2. **Scaffold the Page:** Run `just wikisplain \"<Concept>\" --context <context> --definition \"<copular definition>\"` to generate the canonical structure.",
        "3. **Write Exposition:** Expand the page with narrative context, invariants, and relationships to other disciplines.",
        "4. **Wikilink Entities:** Use closed-world wikilinks (`[[concept]]` or scoped `[[context/concept]]`) to link related terms.",
        "5. **Verify Compliance:** Run `just gate meta` to ensure `wikilinks` and `wiki lead paragraphs` pass cleanly.",
        "",
        "## Invariants",
        "",
        "- **MOS:LEAD:** The first paragraph must open with `**<Concept>** is ...` matching the `# <Concept>` heading exactly.",
        "- **Closed-World Links:** Wikilinks `[[concept]]` must resolve to an existing wiki page or minted concept.",
        "- **Bounded Context:** Pages must reside in `wiki/<context>/` corresponding to their Bounded Context.",
        "",
    ])


def technical_writing_skill():
    """Technical writing skill fusing Diátaxis, Google style, and Literate Programming (solorepo's DR-171, solorepo's DR-175, solorepo's DR-176, solorepo's DR-187, solorepo's DR-194, solorepo's DR-196), and the rubric governing source bodies (solorepo's DR-207)."""
    desc = record.authored("../.claude/skills/technical-writing/SKILL.md", "description").strip()
    return "\n".join([
        "---",
        "name: technical-writing",
        "description: >-",
        *["  " + line for line in textwrap.wrap(desc, 76)],
        "---",
        "",
        "<!-- Generated by .meta/render.py from assertions/imported/structure.yaml.",
        "     Do not edit by hand: edit the assertion and re-render. -->",
        "",
        "# /technical-writing",
        "",
        "The `/technical-writing` skill operationalizes the character of `work:role/technical-writer` (`work:personality/technical-writer`) and enacts solorepo's DR-194, solorepo's DR-196, and solorepo's DR-198.",
        "",
        "## Two Communication and Authoring Regimes (solorepo's DR-198)",
        "",
        "1. **Conversational Communication Register:** In dialogue, PR review threads, turn responses, and issue comments, speak in the Technical Writer register (`work:personality/technical-writer`): *Spelled out and self-contained. Every citation dereferenced. Assume a reader who was not in the conversation, holds none of its shorthand, and arrives by search some years later. Length is not the cost here; ambiguity is.* This breaks the failure mode of abstruse, cryptic shorthand.",
        "2. **Durable Artifact Authoring Regime:** When authoring or editing durable files in the repository (code docstrings, Decision Records, wiki pages, companion logs), the structure, tone, and density are governed by the **Diátaxis quadrant** being authored. Conversational expansiveness must not be imported into item docstrings: Reference docstrings must remain dry, crisp, and contract-focused, with zero reviewer litigation.",
        "",
        "This standard combines Diátaxis documentation architecture, Google developer style sentences, and solorepo's Literate Programming (solorepo's DR-171, solorepo's DR-175, solorepo's DR-176) and Knowledge Management (solorepo's DR-184, solorepo's DR-185, solorepo's DR-187, solorepo's DR-196) disciplines.",
        "",
        "## Five Overarching Invariants",
        "",
        "1. **Every citation dereferenced (solorepo's DR-134, solorepo's DR-192):** Never leave a bare or unverified claim. A statement attributing a rule or behavior must cite its authority (`solorepo's DR-nnn`, `Article n`, `[[concept]]`). Check source assertions directly or search with `just search <query>` (solorepo's DR-103).",
        "2. **Use the Ubiquitous Language (solorepo's DR-190):** The codebase and LinkML ontologies are the word list. Write `Actor` (not user/bot), `Challenge` (not ticket/issue/story), `Role`, `Remit`, `Persona`.",
        "3. **The Reader's Test (solorepo's DR-175):** Can a reader use this item from its docstring alone without reading commit histories or PR threads?",
        "4. **No Reviewer Litigation in Code (solorepo's DR-171):** Docstrings state usage contracts, parameters, and invariants. They do not argue against past reviewers. The 'why' and trade-offs belong in Decision Records (`DR-nnn.yaml`) or module docstrings. Incident narratives belong in `<module>.history.md`.",
        "5. **The Residue Principle (solorepo's Article 15, solorepo's DR-196):** Pull request descriptions, issue comments, and commit messages are not documentation containers. What fits into any of the four Diátaxis quadrants belongs in a durable repository artifact. What remains is residue, and only residue belongs in a pull request body.",
        "",
        "## The Diátaxis Compass",
        "",
        "Select exactly one mode before writing:",
        "",
        "| Mode | Purpose | In Solorepo | Tone & Rules |",
        "|---|---|---|---|",
        "| **Reference** | Facts for lookup (Understanding + Work) | Public function, class, and method docstrings, LinkML schemas | Dry, complete, sure. Describe parameters, invariants, exceptions. No opinions, no tutorials, no past debate. |",
        "| **Explanation** | Understanding & why (Understanding + Learning) | Decision Records (`DR-nnn.yaml`), module overviews, wiki pages | Anchor on a real 'why' question. Context, constraints, alternatives, trade-offs. |",
        "| **How-To** | Steps to a goal (Action + Work) | `just` recipes, solorepo's `SPECIALIZE.md`, workflow guides | Task-oriented, assume competence, action only. No digressions. 'Do X to achieve Y.' |",
        "| **Tutorial** | Learning by doing (Action + Learning) | Quickstarts, onboarding lessons | Guided, step-by-step, visible results at each step. |",
        "",
        "## Pre-Writing Routing: Where to Write",
        "",
        "Before typing prose for a change, execute this routing tree to select the container:",
        "",
        "1. **Task, recipe, or repeatable procedure:** `justfile` recipe or solorepo's `SPECIALIZE.md` (**How-To**).",
        "2. **Public function, class, schema, or API fact:** item docstring or LinkML schema (**Reference**, solorepo's DR-171, solorepo's DR-175).",
        "3. **Settled architectural choice between alternatives:** Decision Record in `.meta/assertions/decisions/DR-nnn.yaml` (**Explanation**).",
        "4. **Bug, incident, or regression history:** `<module>.history.md` with receipts (**Explanation**).",
        "5. **Enduring domain concept or subsystem overview:** `wiki/<context>/<concept>.md` via `just wikisplain` (**Explanation**, solorepo's DR-184, solorepo's DR-190).",
        "6. **Unrouted residue:** Pull request descriptions hold only transient reviewer handoff notes and links to surviving review threads or promoted Issues (solorepo's Article 15). Never summarize diffs.",
        "",
        "## Container Subordination",
        "",
        "The atomic semantic unit of domain knowledge is the Concept (solorepo's DR-195). Subordinate storage placement to the reader's posture:",
        "- **Schema Gloss:** `vocabulary.yaml` when machine checks and search aliases suffice.",
        "- **Section / Subsection:** `##` or `###` within an existing document when tightly bound to an aggregate.",
        "- **Dedicated Wiki Page:** `wiki/<context>/<concept>.md` when the concept has independent depth, invariants, or broad relevance.",
        "- **Subdirectory:** A folder grouping related concept pages for complex domain aggregates.",
        "",
        "Strictly avoid 'wiki article' (`avoid: [wiki article]`) to protect Charter Articles (solorepo's Article 1, solorepo's Article 15).",
        "",
        "## The Four Permissible Comment Exceptions (solorepo's DR-207)",
        "",
        "These exceptions govern every comment in a source file, at every scope — file header, module level, class body, and function or method body alike. A surprise inside internal code is a defect in the code, not a gap in its narration: rename the symbol, extract the helper, or narrow the type until the implementation reads as its own explanation. Four kinds of comment survive a prune, and no others:",
        "",
        "1. **Legal notices.** Copyright, licensing, and attribution headers a license obliges the file to carry.",
        "2. **Public API contracts.** Item docstrings written as dry Diátaxis Reference contracts, with no reviewer litigation (solorepo's DR-175, solorepo's DR-194). An item is a module, class, function, method, or module-level binding, and a binding's docstring is the string literal directly below its assignment.",
        "3. **Immutable external boundary constraints.** A rule a foreign platform, third-party library, operating system, or wire protocol forces on the code and that you cannot reshape from inside this repository, cited with a dereferenced issue, RFC, or specification reference (solorepo's Article 12). A constraint you own is not this exception: mechanize it instead.",
        "4. **Tool formatting directives.** Markers a formatter or generator reads, such as `# fmt: skip` or `// prettier-ignore`.",
        "",
        "Everything else is knowledge to route, a constraint to mechanize, or a suppression to audit. Each has a section below.",
        "",
        "A comment annotating a module-level constant is not a fifth exception. Say what the binding *is* and it is a Reference contract: move it into the docstring below the assignment, where exception 2 already holds it. Say why the value is what it is and it is Explanation: route it to `wiki/<context>/` or a Decision Record. Narrate the statement beside it — `# Ensure .meta is importable` above the `sys.path` insert that does exactly that — and it has no destination, so it goes.",
        "",
        "## Pruning Routes Knowledge, It Never Destroys It",
        "",
        "A comment worth deleting is rarely a comment worth losing. Before removing non-trivial commentary, send what it knows down the routing tree in **Pre-Writing Routing: Where to Write** above:",
        "",
        "- **Defect narrative, incident, or regression history:** `<module>.history.md`, each account carrying an executable receipt — the check or probe symbol under `.meta/checks/probes/` that fails if the defect returns (solorepo's DR-171, solorepo's DR-209).",
        "- **Architectural rationale, or an alternative weighed and rejected:** a Decision Record in `.meta/assertions/decisions/DR-nnn.yaml`, or an enduring concept page under `wiki/<context>/` (solorepo's DR-184, solorepo's DR-196).",
        "- **An operational instruction — how to run, rebuild, or verify something:** a `justfile` recipe, self-documented by its own comment (solorepo's DR-106).",
        "- **Nothing a reader needs:** delete it. Narration of self-evident steps and commented-out dead code have no destination, and git holds the corpse.",
        "",
        "Write the destination before you delete the line. A prune that skips this step is the one that loses the knowledge.",
        "",
        "## Constraint Mechanization Protocol",
        "",
        "`# must run before X`, `# do not reorder`, `# caller must ensure the directory exists`: each states an invariant that nothing checks. Prose cannot fail a gate, so the invariant holds for exactly as long as the next reader's attention.",
        "",
        "Convert the claim into the cheapest mechanism that fails when it is violated, then prune the prose:",
        "",
        "1. **A type or schema invariant,** when the wrong state can be made unrepresentable.",
        "2. **A runtime precondition** that raises where the assumption is made and names what it expected, so the error message carries what the comment said.",
        "3. **A regression probe** under `.meta/checks/probes/`, or a check under `.meta/checks/`, when the ordering or precondition spans call sites.",
        "",
        "An invariant that resists all three is a rule something outside this repository forces on the code, so it stays as an immutable external boundary constraint (exception 3 of The Four Permissible Comment Exceptions above) with its citation.",
        "",
        "## Suppression Audit Protocol",
        "",
        "Treat every lint and type suppression the diff adds or touches — `# noqa`, `# type: ignore`, `#[allow(...)]` — as an open defect until you have read what it silences. Under `.meta/`, the `meta lints` check already refuses one that carries no `# reason:` on the same line (solorepo's DR-177), and a reason is the floor rather than the justification.",
        "",
        "- **A suppression over a safety, correctness, or type-soundness finding is a defect.** Fix the root cause. The suppression is not the fix; it is the record that nobody looked.",
        "- **A surviving suppression is narrow:** the specific rule or error code, never bare. It earns its keep only as an immutable external boundary constraint (exception 3 of The Four Permissible Comment Exceptions above) — a rule a foreign platform, library, or checker forces on the code — with a dereferenced upstream issue or specification saying why the checker is wrong here.",
        "- **A blanket suppression at file or module scope** hides findings nobody has seen yet, including ones the next change adds under it. Narrow it to the line.",
        "",
        "Run this audit in the pre-handoff pass, over what the branch changed (solorepo's DR-198).",
        "",
        "## Google Developer Style Sentences",
        "",
        "- **Address the reader directly:** Use 'you' in the present tense. Reserve 'will' for things that genuinely occur later.",
        "- **Active voice:** 'The gate checks', not 'is checked by the gate'.",
        "- **Cut dead words:** 'To', not 'in order to'. 'Use', not 'utilize'. 'Do', not 'perform'.",
        "- **Specific over sterile:** Name the exact symbol, file, flag, or command name (`python3 .meta/search.py`, not 'the search script').",
        "- **Vary rhythm:** Mix sentence lengths on purpose. Short sentences land a point. Longer ones carry a fact with its condition or consequence.",
        "",
    ])
