"""Every target a render writes, by the path it lands on, and the table's three readers, all here: what is rendered, what is on disk that nothing renders, and which pages take a `merge=union` driver in `.gitattributes`.
"""

from collections.abc import Callable
from typing import Any

from lib.render import META, bootstraps, decisions, pages, record, skills, writers

TargetFn = Callable[[], str | dict[str, Any] | None]


def gitattributes() -> str:
    """`merge=union` for every path this file writes, from the list that writes them.

    A generated page carries no information its sources do not, and the gate
    byte-compares each one against a fresh render, so the committed copy is
    already pinned to the assertions. That makes a merge conflict in one of
    them a conflict about nothing: whatever git settles on is overwritten by
    the next `just render`, and the gate is red until it is.

    They conflict anyway, and for a reason that will not stop: two branches
    that each record a decision both append a row after the last one in
    `decisions.md`, which is one insertion point and two additions. Minting
    stopped them taking the same number (solorepo's DR-128); it does not stop
    them writing to the same line of the file rendered from the numbers.

    `union` takes both sides rather than asking, and `just render` then puts
    the result in the order the sources give. Where both sides changed one row
    — two entries citing one artifact — union leaves both copies, the gate
    says `rendered prose` and the re-render corrects it. Wrong output that the
    gate already catches, in place of a stop that a human has to clear.

    It is local only: GitHub does not read a repository's `.gitattributes`
    when it merges, so the pull request still reads `CONFLICTING` until the
    rebase is pushed. What this removes is the hand-editing inside that
    rebase, not the label in front of it.

    The list is `TARGETS` itself, so a page added there is covered by the act
    of adding it. Every pattern is anchored with a leading `/`: a pattern with
    no slash in it matches a basename at any depth, so a bare `justfile` would
    union a nested one that no gate byte-compares (solorepo's #194).
    """
    names = {"../.gitattributes"}
    for name, fn in TARGETS.items():
        if fn is gitattributes:
            continue
        result = fn()
        if result is None:
            continue
        if isinstance(result, dict):
            names.update(result.keys())
        else:
            names.add(name)
    paths = sorted(f"/{name.removeprefix('../')}" if name.startswith("../")
                   else f"/.meta/{name}" for name in names)
    return "\n".join([
        "# Generated by .meta/render.py from the list of pages it renders.",
        "# Do not edit by hand: add the page to TARGETS and re-render.",
        "#",
        "# A generated page is pinned to its sources by the gate, so a conflict in",
        "# one is a conflict about nothing. `union` keeps both sides and the next",
        "# `just render` puts them in order (solorepo's DR-143). GitHub ignores",
        "# this file when it merges; it is the rebase here that it spares.",
        "",
    ] + [f"{path} merge=union" for path in paths]) + "\n"

TARGETS: dict[str, TargetFn] = {
    "disciplines.md": pages.disciplines,
    "decisions.md": decisions.decisions,
    "templates/decision.md": decisions.decision_form,
    "charter.md": pages.charter,
    "vocabulary.md": pages.vocabulary,
    "../SPECIALIZE.md": pages.specialize,
    "../justfile": writers.justfile,
    "../.github/PULL_REQUEST_TEMPLATE.md": pages.pull_request_template,
    "../.github/ISSUE_TEMPLATE/challenge.md": pages.issue_template,
    "../.github/ISSUE_TEMPLATE/roadmap.md": pages.roadmap_template,
    "../.claude/skills/pr-first/SKILL.md": skills.pr_first_skill,
    "../.claude/skills/pr-first-reviewer/SKILL.md": skills.pr_first_reviewer_skill,
    "../.claude/skills/wikisplain/SKILL.md": skills.wikisplain_skill,
    "../.claude/skills/search/SKILL.md": skills.search_skill,
    "../.claude/skills/technical-writing/SKILL.md": skills.technical_writing_skill,
    "apm_primitives": writers.apm_primitives,
    "../bootstraps/python/README.md": bootstraps.python_readme,
    "../bootstraps/rust/README.md": bootstraps.rust_readme,
    "../.gitattributes": gitattributes,
}


def rendered() -> dict[str, str]:
    """Every generated path, relative to `.meta/`, mapped to its content.

    A target renders one file or a set of them. Both callers — `cli.main`, which writes,
    and `check.py`'s staleness check — want the flat mapping, so the fan-out is
    resolved once here rather than in each of them.

    Counts are filled last, over every page alike: a sentence citing one is
    prose in the assertions, and which generator carries it to a page is not
    that sentence's business.
    """
    out: dict[str, str] = {}
    for name, fn in TARGETS.items():
        result = fn()
        if result is None:
            continue
        if isinstance(result, dict):
            out.update({k: v.decode("utf-8") if isinstance(v, bytes) else str(v)
                        for k, v in result.items()})
        else:
            out[name] = result
    return {name: record.counted(text) for name, text in out.items()}


def unrendered() -> list[str]:
    """Targets that produce nothing and yet have a file on disk, by name.

    By name and not as a sentence about the name, because both callers key on
    the page: the gate wraps it in prose, and `check_pr.py` asks whether the
    record's index is one of them. A sentence answered that question `False`
    however the page stood.
    """
    return [name for name, fn in TARGETS.items()
            if fn() is None and (META / name).exists()]
