"""The files a render writes that are not prose: the justfile (stereorepo's DR-106) and the APM primitives (stereorepo's DR-172, stereorepo's DR-173).
"""

from typing import Any

from lib.render import META, record


def justfile() -> str:
    """The root's verb surface, rendered so that the one line in it that names
    anything comes from the assertions rather than a list kept beside them
    (stereorepo's DR-106).

    Every recipe invokes a tool under `.meta/` and implements nothing; `just
    --list` is the index. The doc comment on `gate` names what the runner
    takes, read from the Projects and Products asserted, which is the line
    that would otherwise drift when a Project is added. Never copied into a
    seed: a verb in every Project is what stereorepo's DR-092 rejected.
    """
    structure = record.load("assertions/structure.yaml") or {}

    def tail(p: dict[str, Any]) -> str:
        return str(p["id"]).rsplit("/", 1)[-1]

    projects = ", ".join(tail(p) for p in structure.get("projects") or [])
    products = ", ".join(tail(p) for p in structure.get("products") or [])
    takes = (f"any of the Projects: {projects}" if projects else "no Project is asserted yet")
    if products:
        takes += f" — and the Products: {products}"
    lines = [
        "# Generated by .meta/render.py from assertions/structure.yaml. Do not edit by hand:",
        "# edit the assertions and re-render.",
        "#",
        "# The verbs, typed. Every recipe invokes a tool under .meta/ and implements",
        "# nothing; `just --list` is the index (stereorepo's DR-106). Not installed? `uvx --from rust-just just`.",
        "",
        "# every recipe, and what it does",
        "default:",
        "    @just --list --unsorted",
        "",
        f"# every Project's gate — or {takes}",
        "gate *targets:",
        "    .meta/gate {{targets}}",
        "",
        "# every generated page, from the assertions",
        "render:",
        "    uvx --python 3.13 --with pyyaml python .meta/render.py",
        "",
        "# the citations this branch wrote, read against what they name; not a gate",
        'dereference *args:',
        "    uvx --python 3.13 --with linkml --with pyyaml python .meta/dereference.py {{args}}",
        "",
        "# surface unminted candidate terms by keyness and dispersion (stereorepo's DR-234)",
        "terms *args:",
        "    uvx --python 3.13 --with wordfreq python .meta/terms.py {{args}}",
        "",
        "# validate, pack, or compile the APM package (stereorepo's DR-201)",
        "apm *args:",
        "    python3 .meta/apm_compile.py {{args}}",
        "",
        "# instantiate a Project from a language Bootstrap on demand (stereorepo's DR-206)",
        "bootstrap *args:",
        "    uvx --python 3.13 --with pyyaml python .meta/bootstrap.py {{args}}",
    ]

    artifacts = {art["id"] for art in structure.get("artifacts") or [] if "id" in art}

    if "work:artifact/pair" in artifacts:
        lines += [
            "",
            "# the pair loop: carry issues to main (--once, --push, --flight SLUG, --model)",
            "pair *args:",
            "    uv run --quiet --script pair/pair.py run {{args}}",
            "",
            "# groom the backlog issues with no difficulty, and place them in ORDER (--rerank)",
            "groom *args:",
            "    uv run --quiet --script pair/pair.py groom {{args}}",
            "",
            "# what waits on you, what is underway, the running order, and the counts (--json)",
            "pair-status *args:",
            "    uv run --quiet --script pair/pair.py status {{args}}",
            "",
            "# pass the desk check and land it (with a Flight's slug: move it to done/)",
            "pair-accept *args:",
            "    uv run --quiet --script pair/pair.py accept {{args}}",
            "",
            "# fail the desk check: the pair picks up your notes (a Flight's slug: to backlog/)",
            "pair-resume *args:",
            "    uv run --quiet --script pair/pair.py resume {{args}}",
            "",
            "# print the loop's events until --until landed, developer, or flight SLUG",
            "pair-watch *args:",
            "    uv run --quiet --script pair/pair.py watch {{args}}",
        ]

    if "work:artifact/meta-test-specialization" in artifacts:
        lines += [
            "",
            "# Specialization, end to end, in a scratch repository (stereorepo's DR-239, DR-244)",
            "test-specialization *args:",
            "    uvx --python 3.13 --with pyyaml python .meta/test_specialization.py {{args}}",
        ]

    if "work:artifact/meta-adapt" in artifacts:
        lines += [
            "",
            "# plan brownfield adoption for an existing Product repository",
            "adapt *args:",
            "    .meta/adapt.py {{args}}",
        ]

    return "\n".join(lines) + "\n"


def apm_primitives() -> dict[str, str | bytes]:
    """Compiles .meta/assertions/ into .meta/.apm/ primitives and .meta/apm.yml (stereorepo's DR-172, stereorepo's DR-173)."""
    import apm_compile
    return apm_compile.rendered_primitives(META)
