"""The files a render writes that are not prose: the justfile (solorepo's DR-106) and the APM primitives (solorepo's DR-172, solorepo's DR-173, solorepo's DR-174).
"""

from typing import Any

from lib.render import META, record


def justfile() -> str:
    """The root's verb surface, rendered so that the one line in it that names
    anything comes from the assertions rather than a list kept beside them
    (solorepo's DR-106).

    Every recipe invokes a tool under `.meta/` and implements nothing; `just
    --list` is the index. The doc comment on `gate` names what the runner
    takes, read from the Projects and Products asserted, which is the line
    that would otherwise drift when a Project is added. Never copied into a
    seed: a verb in every Project is what solorepo's DR-092 rejected.
    """
    structure = record.load("assertions/structure.yaml") or {}

    def tail(p: dict[str, Any]) -> str:
        return str(p["id"]).rsplit("/", 1)[-1]

    projects = ", ".join(tail(p) for p in structure.get("projects") or [])
    products = ", ".join(tail(p) for p in structure.get("products") or [])
    takes = (f"one Project: {projects}" if projects else "no Project is asserted yet")
    if products:
        takes += f" — or one Product: {products}"
    lines = [
        "# Generated by .meta/render.py from assertions/structure.yaml. Do not edit by hand:",
        "# edit the assertions and re-render.",
        "#",
        "# The verbs, typed. Every recipe invokes a tool under .meta/ and implements",
        "# nothing; `just --list` is the index (solorepo's DR-106). Not installed? `uvx --from rust-just just`.",
        "",
        "# every recipe, and what it does",
        "default:",
        "    @just --list --unsorted",
        "",
        f"# every Project's gate — or {takes}",
        'gate target="":',
        "    .meta/gate {{target}}",
        "",
        "# every generated page, from the assertions",
        "render:",
        "    uvx --python 3.13 --with pyyaml python .meta/render.py",
        "",
        "# the pull request gate: A15, A16, A18, A19",
        "pr n *args:",
        "    python3 .meta/check_pr.py {{n}} {{args}}",
        "",
        "# the subscription: one line per change, exiting on actionable events or when it closes",
        "watch n:",
        "    python3 .meta/check_pr.py {{n}} --watch",
        "",
        "# what this branch owns, and what it still owes",
        "sweep:",
        "    python3 .meta/check_pr.py --sweep",
        "",
        "# evaluate open pull requests and merge the top candidate in order of leverage",
        "merge-manager *args:",
        "    .meta/say/move merge-manager {{args}}",
        "",
        "# what landed for a Challenge, from the record; `.meta/say/post landed <pr>` posts it",
        "landed n:",
        "    uvx --python 3.13 --with pyyaml python .meta/render.py --landed {{n}}",
        "",
        "# what to work on next: pull requests, loops, the milestone, and what is ripe",
        "next:",
        "    python3 .meta/next.py",
        "",
        "# what the workflows cost in time: waiting for a runner, and running",
        "timing *args:",
        "    python3 .meta/timing.py {{args}}",
        "",
        "# count review subagent invocations against the fan-out ceiling (solorepo's DR-191)",
        "agents *args:",
        "    python3 .meta/agents.py {{args}}",
        "",
        "# the citations this branch wrote, read against what they name; not a gate",
        'dereference *args:',
        "    uvx --python 3.13 --with linkml --with pyyaml python .meta/dereference.py {{args}}",
        "",
        "# surface unminted candidate terms by keyness and dispersion (solorepo's DR-234)",
        "terms *args:",
        "    uvx --python 3.13 --with wordfreq python .meta/terms.py {{args}}",
        "",
        "# validate, pack, or compile the APM package via .meta/apm_compile.py (solorepo's DR-201)",
        "apm *args:",
        "    python3 .meta/apm_compile.py {{args}}",
        "",
        "# instantiate a Project from a language Bootstrap on demand (solorepo's DR-206)",
        "bootstrap *args:",
        "    uvx --python 3.13 --with pyyaml python .meta/bootstrap.py {{args}}",
    ]

    artifacts = {art["id"] for art in structure.get("artifacts") or [] if "id" in art}

    if "work:artifact/meta-arc-cluster" in artifacts:
        lines += [
            "",
            "# the optional local cluster this repo's self-hosted runner can use",
            "arc-cluster:",
            "    .meta/arc/cluster",
        ]

    if "work:artifact/meta-arc-deploy" in artifacts:
        lines += [
            "",
            "# deploy or update the self-hosted runner (ARC) this repo's CI uses,",
            "# against whatever cluster kubectl is currently pointed at",
            "arc:",
            "    .meta/arc/deploy",
        ]

    if "work:artifact/meta-test-specialization" in artifacts:
        lines += [
            "",
            "# run automated Specialization end-to-end verification (solorepo's DR-239, solorepo's DR-244)",
            "test-specialization *args:",
            "    python3 .meta/test_specialization.py {{args}}",
        ]

    return "\n".join(lines) + "\n"


def apm_primitives() -> dict[str, str | bytes]:
    """Compiles .meta/assertions/ into .meta/.apm/ primitives and .meta/apm.yml (solorepo's DR-172, solorepo's DR-173, solorepo's DR-174)."""
    import apm_compile
    return apm_compile.rendered_primitives(META)
