# Generated by .meta/render.py from assertions/structure.yaml. Do not edit by hand:
# edit the assertions and re-render.
#
# The verbs, typed. Every recipe invokes a tool under .meta/ and implements
# nothing; `just --list` is the index (stereorepo's DR-329). Not installed? `uvx --from rust-just just`.

# every recipe, and what it does
default:
    @just --list --unsorted

# every Project's gate — or any of the Projects: meta, rust-seed, python-seed, pair, specialization — and the Products: scaffold, rust-standard, python-standard
gate *targets:
    .meta/gate {{targets}}

# every generated page, from the assertions
render:
    uvx --python 3.13 --with pyyaml python .meta/render.py

# the citations this branch wrote, read against what they name; not a gate
dereference *args:
    uvx --python 3.13 --with linkml --with pyyaml python .meta/dereference.py {{args}}

# surface unminted candidate terms by keyness and dispersion (stereorepo's DR-234)
terms *args:
    uvx --python 3.13 --with wordfreq python .meta/terms.py {{args}}

# validate, pack, or compile the APM package (stereorepo's DR-201)
apm *args:
    python3 .meta/apm_compile.py {{args}}

# instantiate a Project from a language Bootstrap on demand (stereorepo's DR-206)
bootstrap *args:
    uvx --python 3.13 --with pyyaml python .meta/bootstrap.py {{args}}

# copy a stereorepo checkout's managed items here and remove what it dropped (stereorepo's DR-315)
sync *args:
    .meta/bundle.py sync {{args}}

# the pair loop: carry issues to main (--once, --push, --flight SLUG, --single-seat, --model, --STAGE-model)
pair *args:
    uv run --quiet --script pair/pair.py run {{args}}

# groom the backlog issues with no difficulty, and place them in ORDER (--rerank)
groom *args:
    uv run --quiet --script pair/pair.py groom {{args}}

# what waits on you, what is underway, the running order, and the counts (--json)
pair-status *args:
    uv run --quiet --script pair/pair.py status {{args}}

# pass the desk check and land it (with a Flight's slug: move it to done/)
pair-accept *args:
    uv run --quiet --script pair/pair.py accept {{args}}

# fail the desk check: the pair picks up your notes (a Flight's slug: to backlog/)
pair-resume *args:
    uv run --quiet --script pair/pair.py resume {{args}}

# print the loop's events until --until landed, developer, or flight SLUG
pair-watch *args:
    uv run --quiet --script pair/pair.py watch {{args}}

# Specialization, end to end, in a scratch repository (stereorepo's DR-347, DR-244)
test-specialization *args:
    uvx --python 3.13 --with pyyaml python .meta/test_specialization.py {{args}}

# tag a release of the APM package and publish it (--dry-run) (stereorepo's DR-320)
release *args:
    uvx --python 3.13 --with pyyaml python .meta/release.py {{args}}

# audit a Project's gate against a language Bootstrap, printing each gap as an Issue (--repository PATH) (stereorepo's DR-353, DR-358)
audit project bootstrap *args:
    .meta/audit.py {{project}} {{bootstrap}} {{args}}

# plan brownfield adoption for an existing Product repository
adapt *args:
    .meta/adapt.py {{args}}
