# Generated by .meta/render.py from assertions/structure.yaml. Do not edit by hand:
# edit the assertions and re-render.
#
# The verbs, typed. Every recipe invokes a tool under .meta/ and implements
# nothing; `just --list` is the index (stereorepo's DR-106). Not installed? `uvx --from rust-just just`.

# every recipe, and what it does
default:
    @just --list --unsorted

# every Project's gate — or one Project: meta, rust-seed, python-seed — or one Product: scaffold, rust-standard, python-standard
gate target="":
    .meta/gate {{target}}

# every generated page, from the assertions
render:
    uvx --python 3.13 --with pyyaml python .meta/render.py

# the citations this branch wrote, read against what they name; not a gate
dereference *args:
    uvx --python 3.13 --with linkml --with pyyaml python .meta/dereference.py {{args}}

# surface unminted candidate terms by keyness and dispersion (stereorepo's DR-234)
terms *args:
    uvx --python 3.13 --with wordfreq python .meta/terms.py {{args}}

# validate, pack, or compile the APM package (stereorepo's DR-201)
apm *args:
    python3 .meta/apm_compile.py {{args}}

# instantiate a Project from a language Bootstrap on demand (stereorepo's DR-206)
bootstrap *args:
    uvx --python 3.13 --with pyyaml python .meta/bootstrap.py {{args}}

# Specialization, end to end, in a scratch repository (stereorepo's DR-239, DR-244)
test-specialization *args:
    python3 .meta/test_specialization.py {{args}}

# plan brownfield adoption for an existing Product repository
adapt *args:
    .meta/adapt.py {{args}}
