# Generated by .meta/render.py from assertions/structure.yaml. Do not edit by hand:
# edit the assertions and re-render.
#
# The verbs, typed. Every recipe invokes a tool under .meta/ and implements
# nothing; `just --list` is the index (solorepo's DR-106). Not installed? `uvx --from rust-just just`.

# every recipe, and what it does
default:
    @just --list --unsorted

# every Project's gate — or one Project: meta, rust-seed, python-seed — or one Product: scaffold, rust-standard, python-standard
gate target="":
    .meta/gate {{target}}

# every generated page, from the assertions
render:
    uvx --with pyyaml python .meta/render.py

# the pull request gate: A15, A16, A18, A19
pr n:
    python3 .meta/check_pr.py {{n}}

# the subscription: one line per change, exiting on actionable events or when it closes
watch n:
    python3 .meta/check_pr.py {{n}} --watch

# what this branch owns, and what it still owes
sweep:
    python3 .meta/check_pr.py --sweep

# evaluate open pull requests and merge the top candidate in order of leverage
merge-manager *args:
    .meta/say/move merge-manager {{args}}

# what landed for a Challenge, from the record; `.meta/say/post landed <pr>` posts it
landed n:
    uvx --with pyyaml python .meta/render.py --landed {{n}}

# what to work on next: pull requests, loops, the milestone, and what is ripe
next:
    python3 .meta/next.py

# what the workflows cost in time: waiting for a runner, and running
timing *args:
    python3 .meta/timing.py {{args}}

# count review subagent invocations against the fan-out ceiling (solorepo's DR-191)
agents *args:
    python3 .meta/agents.py {{args}}

# explain or scaffold a wiki concept following Knowledge Management conventions (solorepo's DR-187)
wikisplain *args:
    python3 .meta/wikisplain.py {{args}}

# the citations this branch wrote, read against what they name; not a gate
dereference *args:
    uvx --with linkml --with pyyaml python .meta/dereference.py {{args}}

# search assertions, decisions, and wiki by meaning (solorepo's DR-103)
search *args:
    uvx --with linkml --with pyyaml python .meta/search.py {{args}}

# surface unminted candidate terms by keyness and dispersion (solorepo's DR-234)
terms *args:
    uvx --with wordfreq python .meta/terms.py {{args}}

# validate, pack, or compile the APM package via .meta/apm_compile.py (solorepo's DR-201)
apm *args:
    python3 .meta/apm_compile.py {{args}}

# instantiate a Project from a language Bootstrap on demand (solorepo's DR-206)
bootstrap *args:
    uvx --with pyyaml python .meta/bootstrap.py {{args}}

# the optional local cluster this repo's self-hosted runner can use
arc-cluster:
    .meta/arc/cluster

# deploy or update the self-hosted runner (ARC) this repo's CI uses,
# against whatever cluster kubectl is currently pointed at
arc:
    .meta/arc/deploy

# run automated Specialization end-to-end verification (solorepo's DR-239, solorepo's DR-244)
test-specialization *args:
    python3 .meta/test_specialization.py {{args}}
