"""The body of `.meta/apm_compile.py`: the assertions compiled to APM primitives, and the harness roots reconciled.

`instructions`, `agents`, `skills` and `bootstrap` each compile a family of
primitives from the assertions; `primitives` holds the table of every one and
writes or checks them; `harness` reconciles the root files every harness
reads; `apm` invokes the `apm` command over the package; `cli` is the command
line the script delegates to.
"""
import pathlib

META = pathlib.Path(__file__).resolve().parents[2]
"""The `.meta/` directory, two levels above this package."""
ROOT = META.parent
"""The repository root."""
BANNER = (
    "<!-- Generated by .meta/apm_compile.py from {src}. Do not edit by hand:\n"
    "     edit the assertions and re-render. -->\n\n"
)
"""The header every compiled primitive opens with, naming the assertion it derives from."""
