"""The Python bootstrap's own APM package: its manifest, instructions and primitives, compiled to `bootstraps/python/.apm/` (solorepo's DR-208).
"""
from __future__ import annotations

import pathlib
import sys

import yaml

from lib.apm_compile import ROOT


def python_bootstrap_manifest() -> str:
    """Generates bootstraps/python/apm.yml manifest per solorepo's DR-208."""
    data = {
        "name": "solorepo-python",
        "version": "0.1.0",
        "description": "Python developer and refactoring skills for solorepo projects",
        "license": "MIT",
        "target": ["claude", "antigravity", "copilot", "codex", "kiro"],
        "type": "hybrid",
    }
    header = (
        "# Generated by .meta/apm_compile.py per solorepo's DR-208. Do not edit by hand:\n"
        "# edit the assertions and re-render.\n\n"
    )
    return header + yaml.dump(data, sort_keys=False)


def python_bootstrap_instructions() -> str:
    """Generates bootstraps/python/.apm/instructions/python-standard.instructions.md per solorepo's DR-208.

    `applyTo` is every `*.py`, which in a portfolio is two kinds of file and not
    one: inherited tooling under `.meta/` and the Projects the assertions declare.
    They take different configuration and different gates, so guidance that named
    only one of them named the wrong one for every `.meta/` file it reached
    (solorepo's DR-212).
    """
    return (
        "---\n"
        "description: Python standard conventions and development guidance across solorepo\n"
        'applyTo: "**/*.py"\n'
        "---\n\n"
        "<!-- Generated by .meta/apm_compile.py from bootstraps/python/README.md. Do not edit by hand:\n"
        "     edit the assertions and re-render. -->\n\n"
        "# Python Standard Guidance\n\n"
        "A portfolio holds two kinds of Python target. Settle which one a file belongs to\n"
        "before running any checker over it; `assertions/structure.yaml` is what settles it,\n"
        "since every Project declares the `gate:` that holds it and a Project is instantiated\n"
        "wherever it was asked for.\n\n"
        "**Repository tooling — `.meta/`.** Inherited by every portfolio. Configured by\n"
        "`.meta/ruff.toml` and `.meta/mypy.ini`, run through `python3` and `uvx`, verified by\n"
        "`just gate meta`. It has no `pyproject.toml`, no `[dependency-groups]` and no\n"
        "`tests/`; its behavioural tests are the probes under `.meta/checks/probes/`. Never\n"
        "create a `pyproject.toml` at the repository root, and never delete an import\n"
        "carrying `# noqa: F401  # reason: ...` — it registers gate steps.\n\n"
        "**A Project workspace.** Owns its `pyproject.toml` and its dependency groups, and is\n"
        "verified by `uv run gate` typed in its own directory. It must satisfy the six\n"
        "project-level disciplines: Literate Programming, Ratchet, Observed Failure, Nothing\n"
        "Unconsumed, Seeded Artifacts, and Written Decisions.\n\n"
        "Give every checker its target's configuration by name; a bare `ruff check .` or\n"
        "`mypy .` at the repository root sweeps both targets under one configuration, which is\n"
        "right for neither. The sixteen skills in this package carry the rest, and\n"
        "`py-quality-setup` holds the contract in full.\n"
    )


def python_bootstrap_primitives(root_dir: pathlib.Path = ROOT) -> dict[str, str | bytes]:
    """Compiles bootstraps/python/ assertions and skills into APM primitives (solorepo's DR-208).

    A skill file that is not UTF-8 text — a diagram beside its markdown, a
    stray `__pycache__/*.pyc` left by importing a skill's script — is copied
    as bytes rather than decoded, named on stderr so the compile still says
    what it carried rather than only reporting how many primitives it wrote.
    """
    py_dir = root_dir / "bootstraps" / "python"
    if not py_dir.is_dir():
        return {}
    out: dict[str, str | bytes] = {}
    out["../bootstraps/python/apm.yml"] = python_bootstrap_manifest()
    out["../bootstraps/python/.apm/instructions/python-standard.instructions.md"] = python_bootstrap_instructions()

    skills_dir = py_dir / "skills"
    if skills_dir.is_dir():
        for item in sorted(skills_dir.rglob("*")):
            if not item.is_file():
                continue
            rel_within_skills = item.relative_to(skills_dir)
            if len(rel_within_skills.parts) >= 2:
                rel_path = f"../bootstraps/python/.apm/skills/{rel_within_skills}"
                raw = item.read_bytes()
                try:
                    out[rel_path] = raw.decode("utf-8")
                except UnicodeDecodeError:
                    print(f"apm_compile: {item.relative_to(root_dir)} is not UTF-8 text; "
                          "copying as bytes", file=sys.stderr)
                    out[rel_path] = raw

    return out
