"""The manifest and the instruction primitives: the Ubiquitous Language and one instructions file per Discipline, compiled from the assertions (solorepo's DR-172).
"""
from __future__ import annotations

import pathlib
from typing import Any

import yaml

from lib.apm_compile import BANNER, META


def load_yaml(path: pathlib.Path) -> Any:
    """Loads a YAML file safely, returning None if the file is absent."""
    return yaml.safe_load(path.read_text(encoding="utf-8")) if path.is_file() else None


def apm_manifest() -> str:
    """Generates .meta/apm.yml package manifest per solorepo's DR-172."""
    data = {
        "name": "solorepo",
        "version": "0.1.0",
        "description": "A scaffold for building software products as a team of one in the agentic AI era",
        "license": "MIT",
        "target": ["claude", "gemini", "copilot", "codex", "kiro"],
        "type": "hybrid",
    }
    header = (
        "# Generated by .meta/apm_compile.py per solorepo's DR-172 and DR-206. Do not edit by hand:\n"
        "# edit the assertions and re-render.\n\n"
    )
    return header + yaml.dump(data, sort_keys=False)


def ubiquitous_language_instructions(meta_dir: pathlib.Path = META) -> str:
    """Compiles Ubiquitous Language into global instructions primitive."""
    vocab_file = meta_dir / "assertions" / "imported" / "vocabulary.yaml"
    data = load_yaml(vocab_file) or {}
    concepts = data.get("concept_set") or []

    lines = [
        "---",
        "description: Ubiquitous Language terms and domain ontology across solorepo",
        'applyTo: "**/*"',
        "---",
        "",
        BANNER.format(src="assertions/imported/vocabulary.yaml").strip(),
        "",
        "# Ubiquitous Language",
        "",
        "Use the vocabulary from the ontology of work in preference to synonyms:",
        "a *Challenge*, not a ticket or story; an *Actor*, not a user or a bot;",
        "a *Persona*, not a generic customer archetype.",
        "",
    ]

    for c in concepts:
        label = c.get("pref_label") or c.get("id", "").rsplit("/", 1)[-1]
        definition = c.get("definition", "").strip()
        scope_note = c.get("scope_note", "").strip()
        lines.append(f"## {label}")
        lines.append("")
        lines.append(definition)
        if scope_note:
            lines.append("")
            lines.append(f"> [!NOTE]\n> {scope_note}")
        lines.append("")

    return "\n".join(lines).strip() + "\n"


def discipline_instructions(meta_dir: pathlib.Path = META) -> dict[str, str]:
    """Compiles declared Disciplines into per-discipline instructions primitives."""
    disc_file = meta_dir / "assertions" / "imported" / "disciplines.yaml"
    data = load_yaml(disc_file) or {}
    disciplines = data.get("disciplines") or []
    out = {}

    for d in disciplines:
        slug = d.get("id", "").rsplit("/", 1)[-1]
        name = d.get("name") or slug
        desc = d.get("description") or ""
        first_line = desc.strip().splitlines()[0] if desc.strip() else name
        apply_to = d.get("applies_to") or "**/*"

        lines = [
            "---",
            "description: >-",
            f"  {name} discipline — {first_line}",
            f'applyTo: "{apply_to}"',
            "---",
            "",
            BANNER.format(src="assertions/imported/disciplines.yaml").strip(),
            "",
            f"# {name}",
            "",
            desc.strip(),
            "",
        ]

        if d.get("judgement"):
            lines.extend(["## Judgement", "", d["judgement"].strip(), ""])

        if d.get("steps"):
            lines.extend(["## Steps", ""])
            for step in d["steps"]:
                lines.append(f"- {step.strip()}")
            lines.append("")

        if d.get("produces"):
            lines.extend(["## Produces", ""])
            for prod in d["produces"]:
                lines.append(f"- {prod.strip()}")
            lines.append("")

        out[f".apm/instructions/{slug}.instructions.md"] = "\n".join(lines).strip() + "\n"

    return out
