#!/usr/bin/env python3
"""Assertion-to-APM compiler generator and harness root reconciliation (solorepo's DR-007, solorepo's DR-172, solorepo's DR-173, solorepo's DR-174, solorepo's DR-199, solorepo's DR-200).

Compiles .meta/assertions/ into .meta/.apm/ primitives as late-bound derived
artifacts (solorepo's #28, solorepo's #342):
- Disciplines map to instructions/ with applyTo globs
- Ubiquitous Language maps to instructions/ubiquitous-language.instructions.md
- Roles, Personalities, and Personas map to agents/
- Capabilities of kind SKILL map to skills/
- Gate and signed channel map to hooks/
- Manifest maps to .meta/apm.yml
- Reconciles harness root files (AGENTS.md, CLAUDE.md symlink)
"""
from __future__ import annotations

import argparse
import json
import pathlib
import shutil
import subprocess
import sys
import textwrap
from typing import Any

try:
    import yaml
except ImportError:
    import subprocess
    cmd = ["uvx", "--with", "pyyaml", "python", str(pathlib.Path(__file__).resolve()), *sys.argv[1:]]
    res = subprocess.run(cmd)
    sys.exit(res.returncode)

META = pathlib.Path(__file__).resolve().parent
ROOT = META.parent
BANNER = (
    "<!-- Generated by .meta/apm_compile.py from {src}. Do not edit by hand:\n"
    "     edit the assertions and re-render. -->\n\n"
)


def _load_yaml(path: pathlib.Path) -> Any:
    """Loads a YAML file safely, returning None if the file is absent."""
    return yaml.safe_load(path.read_text(encoding="utf-8")) if path.is_file() else None


def apm_manifest() -> str:
    """Generates .meta/apm.yml package manifest per solorepo's DR-172."""
    data = {
        "name": "solorepo",
        "version": "0.1.0",
        "description": "A scaffold for building software products as a team of one in the agentic AI era",
        "license": "MIT",
        "target": ["claude", "gemini", "copilot"],
        "type": "hybrid",
    }
    header = (
        "# Generated by .meta/apm_compile.py per solorepo's DR-172. Do not edit by hand:\n"
        "# edit the assertions and re-render.\n\n"
    )
    return header + yaml.dump(data, sort_keys=False)


def ubiquitous_language_instructions(meta_dir: pathlib.Path = META) -> str:
    """Compiles Ubiquitous Language into global instructions primitive."""
    vocab_file = meta_dir / "assertions" / "imported" / "vocabulary.yaml"
    data = _load_yaml(vocab_file) or {}
    concepts = data.get("concept_set") or []

    lines = [
        "---",
        "description: Ubiquitous Language terms and domain ontology across solorepo",
        'applyTo: "**/*"',
        "---",
        "",
        BANNER.format(src="assertions/imported/vocabulary.yaml").strip(),
        "",
        "# Ubiquitous Language",
        "",
        "Use the vocabulary from the ontology of work in preference to synonyms:",
        "a *Challenge*, not a ticket or story; an *Actor*, not a user or a bot;",
        "a *Persona*, not a generic customer archetype.",
        "",
    ]

    for c in concepts:
        label = c.get("pref_label") or c.get("id", "").rsplit("/", 1)[-1]
        definition = c.get("definition", "").strip()
        scope_note = c.get("scope_note", "").strip()
        lines.append(f"## {label}")
        lines.append("")
        lines.append(definition)
        if scope_note:
            lines.append("")
            lines.append(f"> [!NOTE]\n> {scope_note}")
        lines.append("")

    return "\n".join(lines).strip() + "\n"


def discipline_instructions(meta_dir: pathlib.Path = META) -> dict[str, str]:
    """Compiles declared Disciplines into per-discipline instructions primitives."""
    disc_file = meta_dir / "assertions" / "imported" / "disciplines.yaml"
    data = _load_yaml(disc_file) or {}
    disciplines = data.get("disciplines") or []
    out = {}

    for d in disciplines:
        slug = d.get("id", "").rsplit("/", 1)[-1]
        name = d.get("name") or slug
        desc = d.get("description") or ""
        first_line = desc.strip().splitlines()[0] if desc.strip() else name
        apply_to = d.get("applies_to") or "**/*"

        lines = [
            "---",
            "description: >-",
            f"  {name} discipline — {first_line}",
            f'applyTo: "{apply_to}"',
            "---",
            "",
            BANNER.format(src="assertions/imported/disciplines.yaml").strip(),
            "",
            f"# {name}",
            "",
            desc.strip(),
            "",
        ]

        if d.get("judgement"):
            lines.extend(["## Judgement", "", d["judgement"].strip(), ""])

        if d.get("steps"):
            lines.extend(["## Steps", ""])
            for step in d["steps"]:
                lines.append(f"- {step.strip()}")
            lines.append("")

        if d.get("produces"):
            lines.extend(["## Produces", ""])
            for prod in d["produces"]:
                lines.append(f"- {prod.strip()}")
            lines.append("")

        out[f".apm/instructions/{slug}.instructions.md"] = "\n".join(lines).strip() + "\n"

    return out


def agent_primitives(meta_dir: pathlib.Path = META) -> dict[str, str]:
    """Compiles Roles, Personalities, and Personas into agent primitives (solorepo's DR-199, solorepo's DR-200).

    Two kinds of agent, written into one directory. An operational Role — the
    coder, the reviewer, the technical writer — takes the communication style
    of the Personality sharing its slug, and is given write access only where
    the Role writes. A stakeholder Persona compiles to an interrogation
    surrogate for collaborative product and feature design (solorepo's DR-200),
    which reads and never writes.
    """
    authority_file = meta_dir / "assertions" / "imported" / "authority.yaml"
    actors_file = meta_dir / "assertions" / "imported" / "actors.yaml"
    personas_file = meta_dir / "assertions" / "personas.yaml"

    auth_data = _load_yaml(authority_file) or {}
    actors_data = _load_yaml(actors_file) or {}
    personas_data = _load_yaml(personas_file) or {}

    personalities = {p["id"]: p for p in actors_data.get("personalities") or []}
    roles = {r["id"]: r for r in auth_data.get("roles") or []}
    out = {}

    for role_id, r in roles.items():
        role_slug = role_id.rsplit("/", 1)[-1]
        personality_id = f"work:personality/{role_slug}"
        personality = personalities.get(personality_id) or {}
        comm_style = personality.get("communication_style", "").strip()

        tools = {"read": True, "bash": True}
        if role_slug in ("coder", "technical-writer"):
            tools["write"] = True

        tools_yaml = "\n".join(f"  {k}: {str(v).lower()}" for k, v in tools.items())

        lines = [
            "---",
            f"name: {role_slug}",
            "description: >-",
            f"  {r.get('description', '').strip()}",
            "model: inherit",
            "tools:",
            tools_yaml,
            "---",
            "",
            BANNER.format(src="assertions/imported/authority.yaml and actors.yaml").strip(),
            "",
            f"# {r.get('name', role_slug).capitalize()} Agent",
            "",
            f"**Role Remit:** {r.get('description', '').strip()}",
            "",
            "## Conversational Communication Register (solorepo's DR-198, solorepo's DR-199)",
            "",
            comm_style,
            "",
            "## Authoring Invariants",
            "",
            "When authoring durable repository files (code docstrings, Decision Records, wiki pages),",
            "follow the Diátaxis quadrant being authored rather than conversational voice.",
        ]
        if role_slug == "coder":
            lines.extend([
                "Apply the /technical-writing skill before handoff (solorepo's DR-194, solorepo's DR-198, solorepo's DR-207):",
                "keep item docstrings dry Reference contracts without reviewer litigation (solorepo's DR-175),",
                "hold source comments to the four permissible exceptions, mechanize constraints before pruning,",
                "route defect narratives to <module>.history.md with probe receipts (solorepo's DR-171), and audit",
                "suppressions as defects.",
            ])
        lines.append("")
        out[f".apm/agents/{role_slug}.agent.md"] = "\n".join(lines).strip() + "\n"

    for p in personas_data.get("personas") or []:
        persona_slug = p.get("id", "").rsplit("/", 1)[-1]
        name = p.get("name", persona_slug)
        desc = p.get("description", "").strip()
        context = p.get("context", "").strip()

        lines = [
            "---",
            f"name: {persona_slug}",
            "description: >-",
            f"  {desc} Interrogation surrogate for collaborative product and feature design (solorepo's DR-200).",
            "model: inherit",
            "tools:",
            "  read: true",
            "---",
            "",
            BANNER.format(src="assertions/personas.yaml").strip(),
            "",
            f"# {name} (Interrogation Surrogate)",
            "",
            f"You are assuming the Persona of **{name}** for collaborative product and feature design (solorepo's DR-200).",
            "Your role is to evaluate design proposals, workflow ergonomics, and UX against your explicit goals and frustrations.",
            "Do NOT behave as a generic agreeable assistant: push back when proposals violate your preferences or create cognitive drag.",
            "",
            "## Worldview & Context",
            "",
            context,
            "",
        ]

        if p.get("persona_goals"):
            lines.extend(["## Goal Hierarchy", ""])
            for g in p["persona_goals"]:
                gtype = g.get("goal_type", "GOAL")
                statement = g.get("statement", "").strip()
                lines.append(f"- **{gtype}:** {statement}")
            lines.append("")

        if p.get("behaviors"):
            lines.extend(["## Characteristic Behaviors", ""])
            for b in p["behaviors"]:
                lines.append(f"- {b.strip()}")
            lines.append("")

        if p.get("frustrations"):
            lines.extend(["## Rejection Boundaries & Frustrations", ""])
            for f in p["frustrations"]:
                lines.append(f"- {f.strip()}")
            lines.append("")

        if p.get("proficiencies"):
            lines.extend(["## Proficiencies", ""])
            for prof in p["proficiencies"]:
                lines.append(f"- {prof.strip()}")
            lines.append("")

        out[f".apm/agents/{persona_slug}.agent.md"] = "\n".join(lines).strip() + "\n"

    return out


def skill_primitives(meta_dir: pathlib.Path = META) -> dict[str, str]:
    """Compiles Capabilities of kind SKILL and operational skills into skills/ primitives.

    Three sources, each yielding only what the ones before it did not: the
    Capabilities the authority asserts, then the operational skills `render`
    generates, then whatever `.claude/skills/` still holds that neither
    produced. The order is the precedence — an asserted Capability is the
    authority on its own slug — and the mirror exists so that a skill written
    for the harness before it was asserted still reaches the package.
    """
    authority_file = meta_dir / "assertions" / "imported" / "authority.yaml"
    auth_data = _load_yaml(authority_file) or {}
    capabilities = auth_data.get("capability_set") or []
    out = {}

    for cap in capabilities:
        if cap.get("capability_kind") != "SKILL":
            continue
        slug = cap.get("id", "").rsplit("/", 1)[-1]
        desc = cap.get("description", "").strip()

        lines = [
            "---",
            f"name: {slug}",
            "description: >-",
            *["  " + line for line in textwrap.wrap(desc.splitlines()[0], 76)],
            "---",
            "",
            BANNER.format(src="assertions/imported/authority.yaml").strip(),
            "",
            f"# /{slug}",
            "",
            desc,
            "",
        ]
        out[f".apm/skills/{slug}/SKILL.md"] = "\n".join(lines).strip() + "\n"

    try:
        import render
        skill_gens = {
            "pr-first": render.pr_first_skill,
            "pr-first-reviewer": render.pr_first_reviewer_skill,
            "wikisplain": render.wikisplain_skill,
            "technical-writing": render.technical_writing_skill,
        }
        for name, gen_fn in skill_gens.items():
            rel_path = f".apm/skills/{name}/SKILL.md"
            if rel_path not in out:
                content = gen_fn()
                if content:
                    out[rel_path] = content
    except (ImportError, Exception):
        pass

    claude_skills = meta_dir.parent / ".claude" / "skills"
    if claude_skills.is_dir():
        for skill_dir in sorted(claude_skills.iterdir()):
            if not skill_dir.is_dir():
                continue
            skill_md = skill_dir / "SKILL.md"
            if skill_md.is_file():
                rel_path = f".apm/skills/{skill_dir.name}/SKILL.md"
                if rel_path not in out:
                    out[rel_path] = skill_md.read_text(encoding="utf-8")

    return out


def hook_primitives() -> dict[str, str]:
    """Compiles gate and signed channel into hooks/ primitives per solorepo's DR-174."""
    signed_channel_hook = {
        "PreToolUse": [
            {
                "matcher": "Bash",
                "hooks": [
                    {
                        "type": "command",
                        "command": "$CLAUDE_PROJECT_DIR/.meta/hooks/signed_channel.py",
                    }
                ],
            }
        ]
    }

    gate_hook = {
        "Stop": [
            {
                "hooks": [
                    {
                        "type": "command",
                        "command": "$CLAUDE_PROJECT_DIR/.meta/gate",
                    }
                ]
            }
        ]
    }

    return {
        ".apm/hooks/signed-channel.json": json.dumps(signed_channel_hook, indent=2) + "\n",
        ".apm/hooks/gate.json": json.dumps(gate_hook, indent=2) + "\n",
    }


def rendered_primitives(meta_dir: pathlib.Path = META) -> dict[str, str]:
    """All generated APM primitive paths relative to .meta/, mapped to content."""
    primitives: dict[str, str] = {}
    primitives["apm.yml"] = apm_manifest()
    primitives[".apm/instructions/ubiquitous-language.instructions.md"] = ubiquitous_language_instructions(meta_dir)
    primitives.update(discipline_instructions(meta_dir))
    primitives.update(agent_primitives(meta_dir))
    primitives.update(skill_primitives(meta_dir))
    primitives.update(hook_primitives())
    return primitives


def check_root_symlinks(root_dir: pathlib.Path = ROOT) -> list[str]:
    """Checks that root harness documentation symlinks point to AGENTS.md."""
    problems = []
    agents_md = root_dir / "AGENTS.md"
    claude_md = root_dir / "CLAUDE.md"
    gemini_md = root_dir / "GEMINI.md"

    if not agents_md.is_file():
        problems.append("AGENTS.md is missing from repository root")
        return problems

    for link_path in (claude_md, gemini_md):
        if not link_path.is_symlink():
            problems.append(f"{link_path.name} is not a symlink to AGENTS.md")
        else:
            try:
                target = link_path.resolve()
                if target != agents_md.resolve():
                    problems.append(f"{link_path.name} resolves to {target}, expected {agents_md}")
            except Exception as e:
                problems.append(f"{link_path.name} broken symlink: {e}")
    return problems


def reconcile_root(root_dir: pathlib.Path = ROOT) -> list[str]:
    """Reconciles harness root files ensuring AGENTS.md single-source invariance.

    `CLAUDE.md` and `GEMINI.md` are symlinks to `AGENTS.md` and this restores
    them as such, including where one has been replaced by a regular file: an
    external compiler that writes its own copy is the way that happens, and a
    copy is the drift the symlink exists to rule out.
    """
    actions = []
    agents_md = root_dir / "AGENTS.md"
    claude_md = root_dir / "CLAUDE.md"
    gemini_md = root_dir / "GEMINI.md"

    if not agents_md.is_file():
        actions.append("ERROR: AGENTS.md is missing from repository root")
        return actions

    for link_path in (claude_md, gemini_md):
        if link_path.is_symlink():
            target = link_path.resolve()
            if target != agents_md.resolve():
                link_path.unlink()
                link_path.symlink_to("AGENTS.md")
                actions.append(f"Fixed symlink {link_path.name} -> AGENTS.md")
        elif link_path.exists():
            link_path.unlink()
            link_path.symlink_to("AGENTS.md")
            actions.append(f"Restored symlink {link_path.name} -> AGENTS.md from file")
        else:
            link_path.symlink_to("AGENTS.md")
            actions.append(f"Created symlink {link_path.name} -> AGENTS.md")

    return actions


def write_primitives(meta_dir: pathlib.Path = META, root_dir: pathlib.Path = ROOT) -> int:
    """Writes all compiled APM primitives to .meta/.apm/ and reconciles root files."""
    prims = rendered_primitives(meta_dir)
    for rel_path, content in prims.items():
        full_path = meta_dir / rel_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content, encoding="utf-8")

    reconcile_root(root_dir)
    return len(prims)


def check_primitives(meta_dir: pathlib.Path = META, root_dir: pathlib.Path = ROOT) -> list[str]:
    """Checks that on-disk APM primitives match compiled output without drift."""
    stale = []
    prims = rendered_primitives(meta_dir)
    for rel_path, content in prims.items():
        full_path = meta_dir / rel_path
        if not full_path.is_file():
            stale.append(f"{rel_path} is missing")
        elif full_path.read_text(encoding="utf-8") != content:
            stale.append(f"{rel_path} has drifted from assertions")

    stale.extend(check_root_symlinks(root_dir))
    return stale


def run_apm(args: list[str], meta_dir: pathlib.Path = META) -> int:
    """Runs the apm CLI inside meta_dir, passing args (solorepo's DR-201)."""
    apm_bin = shutil.which("apm")
    if not apm_bin:
        print(
            "apm is not installed. Install via 'brew install apm' or "
            "'curl -sSL https://aka.ms/apm-unix | sh'",
            file=sys.stderr,
        )
        return 1
    res = subprocess.run([apm_bin, *args], cwd=str(meta_dir))
    return res.returncode


def validate_apm(meta_dir: pathlib.Path = META, root_dir: pathlib.Path = ROOT) -> int:
    """Validates APM primitives against LinkML assertions and APM CLI schema (solorepo's DR-201)."""
    stale = check_primitives(meta_dir, root_dir)
    if stale:
        print("Internal assertion-to-primitive drift detected:", file=sys.stderr)
        for item in stale:
            print(f"  {item}", file=sys.stderr)
        return 1
    print("Internal assertion-to-primitive projection is up to date.")
    apm_bin = shutil.which("apm")
    if not apm_bin:
        print("Note: apm CLI is not installed; skipping downstream APM engine validation.")
        return 0
    return run_apm(["compile", "--validate"], meta_dir=meta_dir)


def pack_apm(args: list[str], meta_dir: pathlib.Path = META) -> int:
    """Packs the APM project into distributable plugin/bundle artifacts (solorepo's DR-201)."""
    return run_apm(["pack", *args], meta_dir=meta_dir)


def compile_apm(args: list[str], meta_dir: pathlib.Path = META) -> int:
    """Compiles the APM project into target harness directories redirected to root (solorepo's DR-172, solorepo's DR-201)."""
    cmd_args = ["compile", "--root", ".."]
    if not any(a.startswith("-t") or a.startswith("--target") or a == "--all" for a in args):
        cmd_args.extend(["-t", "claude,gemini,copilot"])
    cmd_args.extend(args)
    return run_apm(cmd_args, meta_dir=meta_dir)


def main() -> None:
    """CLI entrypoint for APM compiler, packaging, and root reconciliation (solorepo's DR-201)."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated primitives are stale")
    parser.add_argument("--reconcile", action="store_true", help="Reconcile harness root symlinks only")
    parser.add_argument(
        "command",
        nargs="?",
        choices=["validate", "pack", "compile", "audit", "doctor", "preview"],
        help="APM operation to perform",
    )
    parser.add_argument("extra_args", nargs=argparse.REMAINDER, help="Additional arguments forwarded to apm")
    args = parser.parse_args()

    if args.reconcile:
        actions = reconcile_root()
        if actions:
            print("\n".join(actions))
        else:
            print("Harness root documentation symlinks are intact.")
        sys.exit(0)

    if args.check:
        stale = check_primitives()
        if stale:
            print("APM primitives are stale:")
            for item in stale:
                print(f"  {item}")
            sys.exit(1)
        print("APM primitives are up to date.")
        sys.exit(0)

    if args.command == "validate":
        sys.exit(validate_apm())
    elif args.command == "pack":
        sys.exit(pack_apm(args.extra_args))
    elif args.command == "compile":
        sys.exit(compile_apm(args.extra_args))
    elif args.command in ("audit", "doctor", "preview"):
        sys.exit(run_apm([args.command, *args.extra_args]))

    count = write_primitives()
    print(f"Compiled {count} APM primitives.")


if __name__ == "__main__":
    main()
