#!/usr/bin/env python3
"""Inspect Claude Code execution outputs and activate fallback when enabled (solorepo's DR-178, solorepo's DR-240).

Evaluates whether the automatic Gemini fallback is enabled via `GEMINI_FALLBACK`.
When enabled, any Claude harness failure activates Gemini CLI fallback per solorepo's DR-178's
choice to prevent stalled loops on unhandled crashes, emitting `fallback=true` to
`$GITHUB_OUTPUT` and exporting `AI_AGENT=google-github-actions/run-gemini-cli` to
`$GITHUB_ENV`. An advisory scan (`has_quota_error`) inspects the execution log to
label whether quota or rate limit errors were detected. When disabled (the default
per solorepo's DR-240), the script cleanly emits `fallback=false` to `$GITHUB_OUTPUT`
and skips fallback activation to avoid unexpected pay-as-you-go API consumption.
"""

import json
import os
import pathlib
import sys


def is_toggle_enabled(name: str, default: bool = False) -> bool:
    """Check whether an environment variable matches an accepted truthy allowlist.

    Args:
        name: The environment variable name holding the toggle value.
        default: Fallback boolean value when the variable is unset or empty.

    Returns:
        bool: True if the stripped, lowercased value matches one of ('true', '1',
            'yes', 'on', 'enable', 'enabled'); default if unset or empty; False for
            all other values.
    """
    val = os.environ.get(name)
    if val is None or not val.strip():
        return default
    return val.strip().lower() in ("true", "1", "yes", "on", "enable", "enabled")


def has_quota_error(execution_file: str | pathlib.Path) -> bool:
    """Perform an advisory scan of Claude Code execution output for quota indicators.

    Parses the JSON execution log when valid, checking for HTTP 429 status codes,
    'rate_limit' error fields, or 'limit'/'quota'/'rate' keywords in result fields.
    If JSON parsing fails or finds no match, scans the lowercased raw text for
    substrings ('429', 'rate_limit', 'weekly limit', 'hit your').

    Note that fallback activation is not conditioned on this return value: by solorepo's DR-178
    and solorepo's DR-240, any Claude harness failure activates fallback when the
    toggle is enabled, and this scan exists strictly to label the log output.

    Args:
        execution_file: Path to the execution output file generated by Claude Code.

    Returns:
        bool: True if rate limiting, HTTP 429, or quota exhaustion indicators were
            found; False otherwise.
    """
    path = pathlib.Path(execution_file)
    if not path.is_file():
        return False

    try:
        raw = path.read_text(encoding="utf-8", errors="replace")
    except Exception as e:
        print(f"Error reading {path}: {e}", file=sys.stderr)
        return False

    try:
        data = json.loads(raw)
        entries = data if isinstance(data, list) else [data]
        for item in entries:
            if isinstance(item, dict) and (
                item.get("api_error_status") == 429
                or item.get("error") == "rate_limit"
                or any(k in str(item.get("result", "")).lower() for k in ("limit", "quota", "rate"))
            ):
                return True
    except Exception as e:
        print(f"Error parsing {path}: {e}", file=sys.stderr)

    lowered = raw.lower()
    return any(token in lowered for token in ("429", "rate_limit", "weekly limit", "hit your"))


def main() -> int:
    """Evaluate Claude execution output and trigger Gemini fallback if toggle is enabled.

    When GEMINI_FALLBACK is disabled (the default), prints a diagnostic log, writes
    'fallback=false' to $GITHUB_OUTPUT, and exits 0. When enabled, runs the advisory
    quota scan, logs the activation, writes 'fallback=true' to $GITHUB_OUTPUT, and
    exports AI_AGENT to $GITHUB_ENV.

    Returns:
        int: Exit status code (always 0 to allow downstream workflow steps to read outputs).
    """
    if not is_toggle_enabled("GEMINI_FALLBACK", default=False):
        print("Gemini fallback is disabled (GEMINI_FALLBACK != true); skipping.")
        output_file = os.environ.get("GITHUB_OUTPUT")
        if output_file:
            with pathlib.Path(output_file).open("a", encoding="utf-8") as f:
                f.write("fallback=false\n")
        return 0

    custom_path = os.environ.get("EXECUTION_FILE")
    if custom_path:
        file_path: pathlib.Path | str = custom_path
    else:
        temp_dir = os.environ.get("RUNNER_TEMP", "/tmp")
        file_path = pathlib.Path(temp_dir) / "claude-execution-output.json"

    quota_detected = has_quota_error(file_path)
    print(f"Claude failure detected (quota={quota_detected}); activating Gemini fallback.")

    output_file = os.environ.get("GITHUB_OUTPUT")
    if output_file:
        with pathlib.Path(output_file).open("a", encoding="utf-8") as f:
            f.write("fallback=true\n")
    env_file = os.environ.get("GITHUB_ENV")
    if env_file:
        with pathlib.Path(env_file).open("a", encoding="utf-8") as f:
            f.write("AI_AGENT=google-github-actions/run-gemini-cli\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
