#!/usr/bin/env python3
"""Render the prose satellites from the assertions they describe.

`disciplines.md` and `vocabulary.md` list things that `.meta/assertions/` already
holds. Maintaining both by hand is the drift these Disciplines exist to prevent,
so the prose derives and the assertions are the source.

    uvx --with pyyaml python .meta/render.py           # write
    uvx --with pyyaml python .meta/render.py --check   # fail if stale

Definitions in the vocabulary are one-line glosses. The full reasoning stays on
the class, per Literate Programming; these are for recognising a term, not for
applying it.
"""
import sys, pathlib, yaml

META = pathlib.Path(__file__).parent
BANNER = ("<!-- Generated by .meta/render.py from {src}. Do not edit by hand:\n"
          "     edit the assertions and re-render. -->\n\n")


def load(rel):
    """Missing is a legitimate answer. A portfolio has no scaffold-only
    assertions, so a renderer asking for them gets nothing rather than a crash.
    """
    path = META / rel
    return yaml.safe_load(path.read_text()) if path.exists() else None


def disciplines():
    tbox = load("work/disciplines.yaml")
    abox = {"disciplines": []}
    for rel in ("assertions/disciplines.yaml", "assertions/imported/disciplines.yaml"):
        abox["disciplines"].extend((load(rel) or {}).get("disciplines") or [])
    out = [BANNER.format(src="assertions/disciplines.yaml + assertions/imported/disciplines.yaml"),
           "## Disciplines\n",
           "_Structured ways of working that must be adhered to._\n",
           tbox["description"].strip() + "\n"]
    for d in abox["disciplines"]:
        out.append(f"### {d['name']}\n")
        if d.get("description"):
            out.append(d["description"].strip() + "\n")
        if d.get("judgement"):
            out.append(f"**Where the judgement is.** {d['judgement'].strip()}\n")
        if d.get("steps"):
            out.append("\n".join(f"{i}. {s}" for i, s in enumerate(d["steps"], 1)) + "\n")
        if d.get("produces"):
            out.append("_Produces: " + "; ".join(d["produces"]).rstrip(".") + "._\n")
    return "\n".join(out)


def vocabulary():
    """Imported and domain terms render as one language, which is what a reader
    needs. They are separate files because sync treats them differently, not
    because they are separate vocabularies."""
    abox = {"concept_schemes": [], "concept_set": []}
    for rel in ("assertions/imported/vocabulary.yaml", "assertions/vocabulary.yaml",
                "assertions/domain_vocabulary.yaml"):
        part = load(rel) or {}
        for key in abox:
            abox[key].extend(part.get(key) or [])
    schemes = {s["id"]: s for s in abox["concept_schemes"]}
    out = [BANNER.format(src="assertions/*vocabulary.yaml"),
           "## Vocabulary\n",
           "_The words this repo uses, and what they mean._\n",
           "A Concept is a unit of meaning, not a word — which is why two entries\n"
           "below share a label. Use the preferred label; do not mint a term without\n"
           "the solo. Check DDD first, then this vocabulary, then ask.\n"]
    for sid, scheme in schemes.items():
        members = [c for c in abox["concept_set"] if c.get("in_scheme") == sid]
        if not members:
            continue
        out.append(f"### {scheme['name']}\n")
        out.append(f"_Authority: {scheme.get('authority', 'unstated')}._\n")
        hubs = [c for c in members
                if any(m.get("broader") == c["id"] for m in abox["concept_set"])]
        grouped = {h["id"]: [] for h in hubs}
        loose = []
        for c in members:
            if c in hubs:
                continue
            (grouped[c["broader"]] if c.get("broader") in grouped else loose).append(c)

        def table(rows):
            out.append("| Term | Means | Do not say |\n|---|---|---|")
            for c in rows:
                avoid = ", ".join(c.get("avoid", [])) or "—"
                out.append(f"| **{c['pref_label']}** | {c['definition'].strip()} | {avoid} |")
            out.append("")

        if loose:
            table(loose)
        for h in hubs:
            if grouped[h["id"]]:
                out.append(f"#### {h['pref_label']}\n")
                out.append(f"_{h['definition'].strip()}_\n")
                table(grouped[h["id"]])
        for c in members:
            if c.get("scope_note"):
                out.append(f"**{c['pref_label']}.** {c['scope_note'].strip()}\n")
    collisions = [c for c in abox["concept_set"] if c.get("confusable_with")]
    if collisions:
        by_label = {c["id"]: c["pref_label"] for c in abox["concept_set"]}
        out.append("### Confusables\n")
        out.append("One word, more than one meaning. The hazard a vocabulary "
                   "guards against is\nmore often a collision than a gap.\n")
        out.append("| This | Is not | \n|---|---|")
        for c in collisions:
            others = ", ".join(by_label.get(o, o) for o in c["confusable_with"])
            out.append(f"| **{c['pref_label']}** | {others} |")
        out.append("")
    return "\n".join(out)


def charter():
    """The Charter, numbered, which is the form that makes an Article citable.

    Rendered flat and in order rather than grouped by Discipline: the number is
    the identifier, and a reader arriving from a citation wants to find it by
    counting, not by guessing which Discipline it belongs to.
    """
    abox = load("assertions/imported/charter.yaml") or {}
    rows = abox.get("articles") or []
    if not rows:
        return None
    disciplines = {d["id"]: d["name"] for rel in
                   ("assertions/disciplines.yaml", "assertions/imported/disciplines.yaml")
                   for d in ((load(rel) or {}).get("disciplines") or [])}
    out = [BANNER.format(src="assertions/imported/charter.yaml"),
           "## The Charter\n",
           "_A working agreement. One-line claims that can be held against an artifact_\n"
           "_and found false._\n",
           "Numbered as **stable identifiers**, cited as A1, A2 and so on. A retired\n"
           "Article leaves a **hole** and is never\n"
           "renumbered — a citation that silently comes to mean something else is worse than\n"
           "a dangling one.\n",
           "Where a Discipline is *followed*, an Article is *checked*. Some enforce a\n"
           "Discipline; some stand alone, and need nothing behind them.\n"]
    for inv in rows:
        num = inv["id"].rsplit("/", 1)[-1]
        out.append(f"### A{num}. {inv['statement'].strip()}\n")
        held = disciplines.get(inv.get("enforces"))
        bits = []
        if held:
            bits.append(f"**Enforces** {held}.")
        if inv.get("checked_by"):
            bits.append(f"**Checked by** {inv['checked_by'].strip().rstrip('.')}.")
        if bits:
            out.append(" ".join(bits) + "\n")
        if inv.get("origin"):
            out.append(f"_Why:_ {inv['origin'].strip()}\n")
    return "\n".join(out)


def specialize():
    """The root-level instruction an agent arriving at the repo is pointed to.

    Generated from the Specialization Discipline, so the steps exist once. A
    procedure copied into a second file is a procedure that will disagree with
    itself.
    """
    abox = load("assertions/disciplines.yaml") or {}
    d = next((x for x in abox.get("disciplines", []) if x["name"] == "Specialization"), None)
    if d is None:
        return None   # a portfolio specializes nothing, so it has no such page
    out = [BANNER.format(src="assertions/disciplines.yaml"),
           "# Specialize this scaffold into a portfolio\n",
           "You are looking at **solorepo**, a scaffold for building software products as a\n"
           "team of one in the agentic AI era. Specializing it produces a **Portfolio**:\n"
           "one repo, one Bounded Context, one Ubiquitous Language, holding however many\n"
           "Products and Projects.\n",
           d["description"].strip() + "\n",
           f"**Where the judgement is.** {d['judgement'].strip()}\n",
           "## Steps\n",
           "\n".join(f"{i}. {s}" for i, s in enumerate(d["steps"], 1)) + "\n",
           "_Produces: " + "; ".join(d["produces"]).rstrip(".") + "._\n",
           "## Then\n",
           "Read [`.meta/README.md`](.meta/README.md). Its load map routes to everything\n"
           "else, and is deliberately insufficient on its own.\n"]
    return "\n".join(out)


def form(name):
    """The fenced block of a form in `.meta/templates/`, which is the form itself.

    The prose around it explains the form to whoever fills it in; the fence is
    what GitHub hands them. One copy, and this is the generator reading it —
    Literate Programming's rule applied to a template rather than to a schema.
    """
    text = (META / "templates" / name).read_text()
    fence = text.split("```markdown\n", 1)[1].split("\n```", 1)[0]
    return fence.rstrip("\n") + "\n"


def pull_request_template():
    return form("pull-request.md")


def issue_template():
    return form("issue.md")


def _decision_slots():
    """The slot descriptions from the model, which is where the guidance lives.

    Read as plain YAML rather than through a SchemaView so the renderer keeps its
    one dependency. The form and the record are two views of the same class, and
    a form whose headings were typed by hand would be the third copy of a shape
    the schema already states.
    """
    return (load("work/decisions.yaml") or {}).get("slots") or {}


def _decision_page(d, rows, projects):
    """One decision, whole. The satellite a `@DR-0nn` reference resolves to.

    Everything the index cannot carry lives here, which is the whole of it: a
    reader who has found the number has stopped browsing and needs the entry.
    """
    out = [BANNER.format(src="assertions/decisions.yaml"), f"# {d['name']}\n"]
    stamp = d.get("decided") or ""
    if d.get("recorded") and d["recorded"] != stamp:
        stamp = f"{stamp} — recorded {d['recorded']}"
    line = f"*{stamp}*" if stamp else ""
    if d.get("project"):
        line += f" · {projects.get(d['project'], d['project'])}"
    if d.get("status") == "SUPERSEDED":
        line += f" · **Superseded by** {_link(rows, d['superseded_by'])}"
    if d.get("status") == "WITHDRAWN":
        line += " · **Withdrawn**"
    if line:
        out.append(line.strip() + "\n")
    if d.get("status") == "WITHDRAWN":
        out.append(d["withdrawn_because"].strip() + "\n")
        out.append("<details><summary>What the entry holds</summary>\n")
        out.append(d["rationale"].strip() + "\n")
        out.append("</details>\n")
        return "\n".join(out)
    out.append(d["rationale"].strip() + "\n")
    if d.get("options"):
        out.append("**Options considered.**\n")
        for o in d["options"]:
            mark = "chosen" if o.get("chosen") else "rejected"
            out.append(f"- _{o['name']}_ — {mark}. {o['reason'].strip()}")
        out.append("")
    if d.get("consequences"):
        out.append("**Consequences.**\n")
        out += [f"- {c.strip()}" for c in d["consequences"]]
        out.append("")
    if d.get("falsifier"):
        out.append(f"**What would falsify this.** {d['falsifier'].strip()}\n")
    cites = [("Applies", d.get("applies")), ("Departs from", d.get("departs_from"))]
    bearing = "; ".join(f"{label} {', '.join('A' + a.rsplit('/', 1)[-1] for a in ids)}"
                        for label, ids in cites if ids)
    if bearing:
        out.append(f"**Bearing on the Charter.** {bearing}.\n")
    if d.get("supersedes"):
        out.append("**Supersedes.** "
                   + ", ".join(_link(rows, s) for s in d["supersedes"]) + "\n")
    return "\n".join(out)


def decisions():
    """The decision record: an index that routes, and one page per entry.

    Progressive Disclosure applied to the record itself. Sixty-six entries in one
    page is a file nobody loads to answer one question, and the reasoning a
    reader wants is always a single entry's. So the index carries what is needed
    to *choose* — number, question, status, date — and is deliberately
    insufficient to apply anything, and each entry owns its own page.

    The page names are the reference: `.meta/decisions/DR-011.md` is what a
    conversation types as `@DR-011`, which is why the file is named for the
    number alone and not for a slug of its title.

    A withdrawn entry keeps its page — a number is a stable identifier, and a
    citation must resolve — and is listed under Holes rather than in the record.
    """
    abox = load("assertions/decisions.yaml") or {}
    rows = abox.get("decisions") or []
    if not rows:
        return None
    projects = {p["id"]: p["name"] for p in (load("assertions/structure.yaml") or {}).get("projects") or []}
    out = [BANNER.format(src="assertions/decisions.yaml"),
           "## Decision record\n",
           "_Every decision taken, with why. Newest last._\n",
           "Add an entry when the question is settled, not when the answer is built —\n"
           "`status` says how far it has got. A number is a\n"
           "**stable identifier** and is never reused: an entry that turned out to record a\n"
           "narrative rather than a foreclosure is withdrawn, and its number stays a hole\n"
           "at the foot of this page.\n",
           "**This page routes and does not restate.** Each entry is its own file under\n"
           "[`decisions/`](decisions/), named for its number so a conversation can reach it\n"
           "as `@.meta/decisions/DR-011.md`. The line here tells you an entry exists and\n"
           "what question it answered; only the entry is sufficient to apply it.\n",
           "| Entry | The question it settled | Status | Decided |",
           "| :-- | :-- | :-- | :-- |"]
    files = {}
    holes = []
    for d in rows:
        num = d["id"].rsplit("/", 1)[-1]
        files[f"decisions/DR-{num}.md"] = _decision_page(d, rows, projects)
        if d.get("status") == "WITHDRAWN":
            holes.append(d)
            continue
        status = (d.get("status") or "").capitalize()
        if d.get("status") == "SUPERSEDED":
            status = f"Superseded by {_link(rows, d['superseded_by'], 'decisions/')}"
        title = d["name"].split(" · ", 1)[-1]
        if d.get("project"):
            title += f" · {projects.get(d['project'], d['project'])}"
        out.append(f"| [DR-{num}](decisions/DR-{num}.md) | {title} | {status} | {d.get('decided') or ''} |")
    out.append("")
    if holes:
        out.append("## Holes\n")
        out.append("Numbers that were issued and are not decisions. They are never reused, and\n"
                   "the prose is kept: a paragraph that was worth writing does not stop being\n"
                   "true because it turned out to foreclose nothing.\n")
        for d in holes:
            num = d["id"].rsplit("/", 1)[-1]
            why = " ".join(d["withdrawn_because"].strip().split())
            out.append(f"- [DR-{num}](decisions/DR-{num}.md) — withdrawn. "
                       + why.split(". ")[0].rstrip(".") + ".")
        out.append("")
    files["decisions.md"] = "\n".join(out)
    return files


def _link(rows, ident, prefix=""):
    """A supersession names another entry, and now that entry is a page.

    Rendered as a link rather than bare text, because the reference is the point:
    the reader who has just been told this was superseded wants the entry that
    superseded it, not its number.
    """
    for d in rows:
        if d["id"] == ident:
            num = d["id"].rsplit("/", 1)[-1]
            return f"[{d['name'].split(' · ')[0]}]({prefix}DR-{num}.md)"
    return ident


def adr_template():
    """The Project-level form, rendered from the same class the record uses.

    A Portfolio decision and a Project's ADR are one class with `project` set or
    not (DR-058), so the form's headings are the model's slots and its guidance
    is their descriptions. Typing them here as well would be the copy that
    disagrees — and the copy that keeps a form asking for something the model
    stopped requiring.
    """
    slots = _decision_slots()
    if not slots:
        return None

    def guidance(name):
        return " ".join(slots[name]["description"].split())

    out = [BANNER.format(src="work/decisions.yaml"),
           "# ADR-<nnnn>: <one-line title, present tense>\n",
           "**Not authoritative.** The Charter and the Disciplines hold the rules and win\n"
           "any disagreement. This records why one Project is built the way it is, and it\n"
           "is a `Decision` with its `project` set — the same class as an entry in\n"
           "`.meta/decisions.md`, filed where the people it binds will find it.\n",
           "- **Status:** <" + " | ".join(
               (load("work/decisions.yaml") or {})["enums"]["DecisionStatus"]["permissible_values"]) + ">",
           "- **Project:** <which Project this is about>",
           "- **Decided:** <date> — **Recorded:** <date>\n",
           guidance("decided").split(". ", 1)[1] + "\n",
           "## Context\n", "<" + guidance("context") + ">\n",
           "## Decision\n",
           "<What was decided, in the present tense — \"we do X\". One paragraph.>\n",
           "## Options considered\n",
           "<" + guidance("options") + ">\n",
           "### A: <option> — rejected\n", "<" + guidance("reason") + ">\n",
           "### B: <option> — chosen\n", "<As above, including what it costs.>\n",
           "## Consequences\n", "<" + guidance("consequences") + ">\n",
           "## What would falsify this\n", "<" + guidance("falsifier") + ">\n",
           "## Bearing on the Charter\n",
           "Dereference every citation per A12 — \"A9 — a seed is data, gated by "
           "rendering it\"\nrather than a bare \"A9\". Omit the section if there is "
           "none.\n",
           "- **Applies:** <" + guidance("applies") + ">",
           "- **Departs from:** <" + guidance("departs_from") + ">\n",
           "## Supersedes\n",
           "<" + guidance("supersedes") + " Omit the section if there is none.>\n"]
    return "\n".join(out)


def _discipline(name):
    for rel in ("assertions/disciplines.yaml", "assertions/imported/disciplines.yaml"):
        for d in (load(rel) or {}).get("disciplines") or []:
            if d["name"] == name:
                return d
    return None


def skill(name, discipline, trigger, commands, forms=()):
    """A Discipline, compiled for this harness.

    A skill is a Discipline plus the commands that carry it out, in the shape one
    harness loads on demand. Everything here is read from the assertions — the
    steps, the judgement, the Articles that enforce it, and any form's own fence.
    Nothing is restated, because a skill that restated the Discipline would be
    the copy nothing checks, and the one an agent actually reads.

    Only the Claude Code target is emitted. The frontmatter an APM primitive
    wants is still unverified (DR-040), and writing plausible field names would
    be worse than the gap; this is the same compilation at the scale that can be
    tested today.
    """
    d = _discipline(discipline)
    if d is None:
        return None
    articles = [a for a in ((load("assertions/imported/charter.yaml") or {}).get("articles") or [])
                if a.get("enforces") == d["id"]]
    out = ["---", f"name: {name}", "description: >-"]
    out += ["  " + line for line in trigger]
    out += ["---\n",
            "<!-- Generated by .meta/render.py from assertions/imported/disciplines.yaml.",
            "     Do not edit by hand: edit the assertion and re-render. -->\n",
            f"# {d['name']}\n",
            d["description"].strip() + "\n",
            "## Steps\n",
            "\n".join(f"{i}. {s.strip()}" for i, s in enumerate(d["steps"], 1)) + "\n",
            "## Where the judgement is\n",
            d["judgement"].strip() + "\n",
            "**None of the below decides any of the above.** A script can tell you a thread",
            "is unanswered, or a branch unpushed. What to write, and whether a point is",
            "right, is yours.\n",
            "## Commands\n", "```bash", *commands, "```\n"]
    for title, form_name, note in forms:
        out += [f"## {title}\n", note + "\n", "```markdown",
                form(form_name).rstrip("\n"), "```\n"]
    if articles:
        out.append("## What is checked\n")
        for a in articles:
            out.append(f"- **A{a['id'].rsplit('/', 1)[-1]}.** {a['statement'].strip()}")
        out.append("")
    return "\n".join(out)


def pr_first_skill():
    return skill(
        "pr-first", "PR First",
        ["Open, argue in, watch and close a pull request the way this repository",
         "requires. Use when starting any change, when a review or comment lands on",
         "one, and when picking work up again — an open pull request this branch owns",
         "with an unanswered thread is work in progress, whoever noticed it."],
        ["python3 .meta/check_pr.py --sweep          # what this branch owns, and what it owes",
         "python3 .meta/check_pr.py <n> --threads    # the threads still owed an answer",
         "python3 .meta/check_pr.py <n>              # the gate: A15 and A16"],
        [("The body", "pull-request.md",
          "Fill this in when the work **starts**. `check_pr.py` reads the same form, so a\n"
          "heading added here is required by that act alone.")])


TARGETS = {"disciplines.md": disciplines,
           "decisions.md": decisions,
           "templates/adr.md": adr_template,
           "charter.md": charter,
           "vocabulary.md": vocabulary,
           "../SPECIALIZE.md": specialize,
           "../.github/PULL_REQUEST_TEMPLATE.md": pull_request_template,
           "../.github/ISSUE_TEMPLATE/challenge.md": issue_template,
           "../.claude/skills/pr-first/SKILL.md": pr_first_skill}

# Directories whose every `.md` is generated, so a file left behind when its
# source went away is a stale copy rather than someone's page. A target that
# renders many files needs this: dropping an entry stops writing its file, and
# nothing else would notice the orphan.
SWEPT = ("decisions",)


def rendered():
    """Every generated path, relative to `.meta/`, mapped to its content.

    A target renders one file or a set of them. Both callers — the writer below
    and `check.py`'s staleness check — want the flat mapping, so the fan-out is
    resolved once here rather than in each of them.
    """
    out = {}
    for name, fn in TARGETS.items():
        result = fn()
        if result is None:
            continue
        out.update(result if isinstance(result, dict) else {name: result})
    return out


def orphans(paths):
    """Generated files under a swept directory that nothing renders."""
    want = {(META / p).resolve() for p in paths}
    return sorted(f for d in SWEPT for f in (META / d).glob("*.md")
                  if f.resolve() not in want)


def unrendered():
    """Targets that produce nothing and yet have a file on disk."""
    return [f"{name} exists but nothing renders it" for name, fn in TARGETS.items()
            if fn() is None and (META / name).exists()]


if __name__ == "__main__":
    check = "--check" in sys.argv
    pages = rendered()
    stale = unrendered()
    for name, text in pages.items():
        path, want = META / name, text.rstrip("\n") + "\n"
        if check:
            if not path.exists() or path.read_text() != want:
                stale.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(want)
    for path in orphans(pages):
        if check:
            stale.append(f"{path.relative_to(META)} is generated and nothing renders it")
        else:
            path.unlink()
    if check:
        print("stale: " + ", ".join(stale) if stale else "up to date")
        sys.exit(1 if stale else 0)
    print(f"wrote {len(pages)} files")
