#!/usr/bin/env python3
"""Render the prose satellites from the assertions they describe.

`disciplines.md` and `vocabulary.md` list things that `.meta/assertions/` already
holds. Maintaining both by hand is the drift these Disciplines exist to prevent,
so the prose derives and the assertions are the source (solorepo's DR-026). The decision
record joined them once it too was assertions (solorepo's DR-059), and PR First compiles the
same way into a skill (solorepo's DR-060).

    uvx --with pyyaml python .meta/render.py           # write
    uvx --with pyyaml python .meta/render.py --check   # fail if stale
    uvx --with pyyaml python .meta/render.py --landed 11   # what a Challenge got

Definitions in the vocabulary are one-line glosses. The full reasoning stays on
the class, per Literate Programming; these are for recognising a term, not for
applying it.
"""
import ast
import pathlib
import posixpath
import re
import sys
import textwrap

import yaml

META = pathlib.Path(__file__).parent
# An entry *is* its assertion file. Two spellings of the same path: one from the
# repository root, one from `.meta/`, where `decisions.md` sits.
RECORD = ".meta/assertions/decisions/DR-{}.yaml"
ENTRY = "assertions/decisions/DR-{}.yaml"

BANNER = ("<!-- Generated by .meta/render.py from {src}. Do not edit by hand:\n"
          "     edit the assertions and re-render. -->\n\n")

# Every block of authored prose a render asked for, as `(host, slot, block)`,
# filled as `authored()` and `woven()` are called. `host` is the Artifact's
# path or the Discipline's id, and `block` is the woven block's name — empty
# where the slot is the whole block. The gate holds this against where the
# prose is asserted, in both directions: prose asserted in the file
# Specialization replaces, and prose asserted that nothing asks for. A set read
# from a run is the set, because a list typed beside the call sites would be
# the second copy all of this exists to remove (solorepo's DR-144, DR-152).
ASKED = set()


def load(rel):
    """Missing is a legitimate answer. A portfolio has no scaffold-only
    assertions, so a renderer asking for them gets nothing rather than a crash.
    """
    path = META / rel
    return yaml.safe_load(path.read_text()) if path.exists() else None


def record():
    """Every Decision, newest last, from one file per entry.

    One entry is one file so that adding or editing one costs that file rather
    than the whole record. `check.py` needs no change for it — its collector
    already walks `assertions/` — and the numbering is the sort, so the directory
    listing is the order.
    """
    rows = []
    for path in sorted((META / "assertions" / "decisions").glob("DR-*.yaml")):
        rows += (yaml.safe_load(path.read_text()) or {}).get("decisions") or []
    return rows


def all_artifacts():
    """Every Artifact asserted, inherited and the portfolio's own.

    Two files for the same reason the Disciplines and the Vocabulary have two:
    `assertions/imported/` is what Specialization copies, and
    `assertions/structure.yaml` is the portfolio's own and never synced. The
    pages a portfolio renders are the scaffold's, so the Artifacts carrying
    their prose are inherited; `SPECIALIZE.md`'s is not, because a portfolio
    has no such page.
    """
    return [a for rel in ("assertions/imported/structure.yaml", "assertions/structure.yaml")
            for a in (load(rel) or {}).get("artifacts") or []]


def artifacts():
    """Artifact id -> path, from the assertions."""
    return {a["id"]: a["path"] for a in all_artifacts()}


def authored(target, slot="preamble"):
    """The prose a generated page opens or closes with, from its Artifact.

    `render.py` writes pages and does not author them: a generator carrying
    prose of its own is a second author, and the drift it was built to prevent
    (solorepo's DR-144). `target` is the path as `TARGETS` names it, relative
    to `.meta/`, which is the same path the Artifact asserts.

    Missing is an error and not an empty page. A `None` spliced into the list
    this returns into arrives as `sequence item 1: expected str` several frames
    away, which is the shape A7 says a step does not print; named here, a
    renamed `path` or a dropped slot says which page and which slot.
    """
    rel = posixpath.normpath(posixpath.join(".meta", target))
    ASKED.add((rel, slot, ""))
    for a in all_artifacts():
        if a["path"] == rel and a.get(slot):
            return a[slot].strip() + "\n"
    raise LookupError(f"no Artifact asserts a {slot} for {rel}, "
                      f"which {target} is rendered from")


# A count about the record, cited in prose as `{#name}` and filled by the
# render. A number an author typed is true the day it is typed and silently
# false one landing later: step two of Specialization said "three of
# `check.py`'s four prechecks load the channel or a hook" across the two
# landings that added a fifth precheck and a sixth, and that sentence is the
# reason the procedure gives for copying the channel into a portfolio
# (solorepo's #231). Filled here it is held by `rendered prose`, which compares
# the committed page against a fresh render: the count moves, the page is
# stale, the gate says so — so the arithmetic is the render's and no step of
# the gate is added to hold it (solorepo's DR-154).
COUNT = re.compile(r"\{#(?P<name>[a-z][a-z ]*[a-z])\}")

# Small counts as the words a sentence wants. The number is filled into the
# middle of a sentence somebody wrote, where a numeral reads as a citation
# rather than as a quantity; past twelve the word is the harder read and the
# digits win.
NUMBERS = ("no", "one", "two", "three", "four", "five", "six", "seven", "eight",
           "nine", "ten", "eleven", "twelve")


def prechecks():
    """The gate's prechecks, by function name, read out of the modules that
    register them.

    Read and not imported. The renderer has one dependency — `uvx --with pyyaml
    python .meta/render.py` is how it is run, and how `check.py` runs it — and
    the modules a count of the gate's steps reaches into have LinkML. Each step
    registers itself at its definition, so `@check(..., pre=True)` is the
    declaration, and `ast` reads it without running anything.

    The steps live in `.meta/checks/`, one module per subject
    (solorepo's DR-150), so the whole directory is read rather than one file:
    which module a precheck is written in is that split's business, and a count
    of them should not move when one is carried from one subject to another.

    Empty is an error and not a count of none. A rewrite that registers steps
    some other way says so here, rather than leaving the prose that cites this
    to assert there are no prechecks at all.
    """
    found = []
    for path in sorted((META / "checks").glob("*.py")):
        for node in ast.parse(path.read_text()).body:
            for decorator in getattr(node, "decorator_list", []):
                if not (isinstance(decorator, ast.Call)
                        and getattr(decorator.func, "id", None) == "check"):
                    continue
                if any(word.arg == "pre" and getattr(word.value, "value", None) is True
                       for word in decorator.keywords):
                    found.append(node.name)
    if not found:
        raise LookupError("no module in .meta/checks/ registers a step with "
                          "`@check(..., pre=True)`, and a count cited in prose is "
                          "derived from those that are")
    return found


def counts():
    """What prose may cite a count of, each derived from the thing counted."""
    return {"prechecks": len(prechecks())}


def counted(text):
    """Every count the prose of a page cites, filled.

    Applied to the finished page rather than to each scalar as it is read, so
    that a count can be cited from any prose the assertions hold and no
    generator has to remember to ask for it.

    A name nothing derives is an error and not a number invented, for the
    reason `authored()` gives: an unfilled `{#...}` reaching a page is the
    drift this exists to remove, printed.
    """
    table = counts()

    def fill(m):
        if m["name"] not in table:
            raise LookupError(
                f"prose cites a count of {m['name']}, which nothing derives; "
                f"the counts are {', '.join(sorted(table))}")
        n = table[m["name"]]
        return NUMBERS[n] if n < len(NUMBERS) else str(n)

    return COUNT.sub(fill, text)


def woven(host, block, **holes):
    """A named block of the prose a generator writes *between* what it derives.

    `preamble` and `postamble` are identified by where they sit; a block in the
    middle of a page is not, so it carries a name and is asked for by it
    (solorepo's DR-152). A block hangs off what it frames, which is what `host`
    says: a page's path, as `TARGETS` spells it, where the block belongs to that
    one Artifact; a Discipline, where every reading compiled from it carries the
    same block and one copy per page would be the second copy.

    `holes` fills the block's named holes — `{role}` — and filling one is the
    whole of what a generator may add to prose it is handed. A block with no
    holes is never formatted, so a stray brace in the prose is prose.

    Missing is an error naming the host and the block, for the reason
    `authored()` gives: a dropped block arrives frames away from its cause.
    """
    if isinstance(host, str):
        rel = posixpath.normpath(posixpath.join(".meta", host))
        ASKED.add((rel, "woven", block))
        where = rel
        host = next((a for a in all_artifacts()
                     if a["path"] == rel and any(p.get("name") == block for p in a.get("woven") or [])), {})
    else:
        where = host["id"]
        ASKED.add((where, "woven", block))
    for prose in host.get("woven") or []:
        if prose["name"] == block:
            text = prose["text"].strip()
            return text.format(**holes) if holes else text
    raise LookupError(f"{where} asserts no woven block named {block!r}")


def accounted_by(target):
    """The DRs naming this page under `enacted_in`, as A20's back-pointer.

    Rendered rather than typed, so `enacted_in` stays the only statement of the
    link. Hand-written artifacts cite the number in prose instead, which is what
    `check.py` holds them to.

    `target` is the path as `TARGETS` names it, relative to `.meta/`.
    """
    rel = posixpath.normpath(posixpath.join(".meta", target))
    rows = record()
    paths = artifacts()
    here = posixpath.dirname(rel)
    cited = [d for d in rows
             if rel in [paths.get(a, a) for a in (d.get("enacted_in") or [])]]
    if not cited:
        return ""
    links = ", ".join(
        f"[DR-{d['id'].rsplit('/', 1)[-1]}]"
        f"({posixpath.relpath(RECORD.format(d['id'].rsplit('/', 1)[-1]), here)})"
        for d in cited)
    return "\n---\n\n**Where this came from.** " + links + "\n"


def disciplines():
    """Renders the disciplines catalog markdown from declared and imported disciplines."""
    tbox = load("work/disciplines.yaml")
    abox = {"disciplines": []}
    for rel in ("assertions/disciplines.yaml", "assertions/imported/disciplines.yaml"):
        abox["disciplines"].extend((load(rel) or {}).get("disciplines") or [])
    out = [BANNER.format(src="assertions/disciplines.yaml + assertions/imported/disciplines.yaml"),
           authored("disciplines.md"),
           tbox["description"].strip() + "\n"]
    for d in abox["disciplines"]:
        out.append(f"### {d['name']}\n")
        if d.get("description"):
            out.append(d["description"].strip() + "\n")
        if d.get("judgement"):
            out.append(f"**Where the judgement is.** {d['judgement'].strip()}\n")
        if d.get("steps"):
            out.append("\n".join(f"{i}. {s}" for i, s in enumerate(d["steps"], 1)) + "\n")
        if d["name"] == (channel() or {}).get("discipline"):
            out.append("The verbs are the steps, and each refuses its own misuse (solorepo's DR-116). Every act\n"
                       "on GitHub goes through the channel, `.meta/say/`, which names the Actor in\n"
                       "every commit and every comment; which Role holds each verb is\n"
                       "`.meta/say/verbs.yaml`'s to say, and a Role's reading lists\n"
                       "only its own (solorepo's DR-117).\n")
            for program in channel()["programs"]:
                out.append(f"**`.meta/say/{program['name']}`** — {program['concern'].strip()}\n")
                out.append("\n".join(f"- `{verb_line(program, v)}` — {v['does']} *({', '.join(v['held_by'])})*"
                                      for v in program["verbs"]) + "\n")
        if d.get("produces"):
            out.append("_Produces: " + "; ".join(d["produces"]).rstrip(".") + "._\n")
    return "\n".join(out) + accounted_by("disciplines.md")


def vocabulary():
    """Imported and domain terms render as one language, which is what a reader
    needs. They are separate files because sync treats them differently, not
    because they are separate vocabularies."""
    abox = {"concept_schemes": [], "concept_set": []}
    for rel in ("assertions/imported/vocabulary.yaml", "assertions/vocabulary.yaml",
                "assertions/domain_vocabulary.yaml"):
        part = load(rel) or {}
        for key in abox:
            abox[key].extend(part.get(key) or [])
    schemes = {s["id"]: s for s in abox["concept_schemes"]}
    out = [BANNER.format(src="assertions/*vocabulary.yaml"),
           authored("vocabulary.md")]
    for sid, scheme in schemes.items():
        members = [c for c in abox["concept_set"] if c.get("in_scheme") == sid]
        if not members:
            continue
        out.append(f"### {scheme['name']}\n")
        out.append(f"_Authority: {scheme.get('authority', 'unstated')}._\n")
        hubs = [c for c in members
                if any(m.get("broader") == c["id"] for m in abox["concept_set"])]
        grouped = {h["id"]: [] for h in hubs}
        loose = []
        for c in members:
            if c in hubs:
                continue
            (grouped[c["broader"]] if c.get("broader") in grouped else loose).append(c)

        def table(rows):
            out.append("| Term | Means | Do not say |\n|---|---|---|")
            for c in rows:
                avoid = ", ".join(c.get("avoid", [])) or "—"
                out.append(f"| **{c['pref_label']}** | {c['definition'].strip()} | {avoid} |")
            out.append("")

        if loose:
            table(loose)
        for h in hubs:
            if grouped[h["id"]]:
                out.append(f"#### {h['pref_label']}\n")
                out.append(f"_{h['definition'].strip()}_\n")
                table(grouped[h["id"]])
        for c in members:
            if c.get("scope_note"):
                out.append(f"**{c['pref_label']}.** {c['scope_note'].strip()}\n")
    collisions = [c for c in abox["concept_set"] if c.get("confusable_with")]
    if collisions:
        by_label = {c["id"]: c["pref_label"] for c in abox["concept_set"]}
        out.append("### Confusables\n")
        out.append("One word, more than one meaning. The hazard a vocabulary "
                   "guards against is\nmore often a collision than a gap.\n")
        out.append("| This | Is not | \n|---|---|")
        for c in collisions:
            others = ", ".join(by_label.get(o, o) for o in c["confusable_with"])
            out.append(f"| **{c['pref_label']}** | {others} |")
        out.append("")
    return "\n".join(out) + accounted_by("vocabulary.md")


def charter():
    """The Charter, numbered, which is the form that makes an Article citable.

    Rendered flat and in order rather than grouped by Discipline: the number is
    the identifier, and a reader arriving from a citation wants to find it by
    counting, not by guessing which Discipline it belongs to.
    """
    abox = load("assertions/imported/charter.yaml") or {}
    rows = abox.get("articles") or []
    if not rows:
        return None
    disciplines = {d["id"]: d["name"] for rel in
                   ("assertions/disciplines.yaml", "assertions/imported/disciplines.yaml")
                   for d in ((load(rel) or {}).get("disciplines") or [])}
    out = [BANNER.format(src="assertions/imported/charter.yaml"),
           authored("charter.md")]
    # Retired numbers sit in sequence, one line each. A reader scanning the
    # Charter needs to know the gap is a gap; why it is one is the retiring
    # entry's, and reaching it costs a grep, which is the point.
    holes = {h["number"]: h for h in abox.get("retired_articles") or []}
    live = {int(a["id"].rsplit("/", 1)[-1]): a for a in rows}
    for num in sorted(live | holes):
        if num in holes:
            out.append(f"### A{num}. Retired.\n")
            continue
        inv = live[num]
        out.append(f"### A{num}. {inv['statement'].strip()}\n")
        held = disciplines.get(inv.get("enforces"))
        bits = []
        if held:
            bits.append(f"**Enforces** {held}.")
        if inv.get("checked_by"):
            bits.append(f"**Checked by** {inv['checked_by'].strip().rstrip('.')}.")
        if bits:
            out.append(" ".join(bits) + "\n")
        if inv.get("example"):
            out.append(f"_In practice:_ {inv['example'].strip()}\n")
        if inv.get("falsifier"):
            out.append(f"_Retired when:_ {inv['falsifier'].strip()}\n")
    return "\n".join(out) + accounted_by("charter.md")


def specialize():
    """The root-level instruction an agent arriving at the repo is pointed to.

    Generated from the Specialization Discipline, so the steps exist once. A
    procedure copied into a second file is a procedure that will disagree with
    itself.
    """
    abox = load("assertions/disciplines.yaml") or {}
    d = next((x for x in abox.get("disciplines", []) if x["name"] == "Specialization"), None)
    if d is None:
        return None   # a portfolio specializes nothing, so it has no such page
    out = [BANNER.format(src="assertions/disciplines.yaml"),
           authored("../SPECIALIZE.md"),
           d["description"].strip() + "\n",
           f"**Where the judgement is.** {d['judgement'].strip()}\n",
           "## Steps\n",
           "\n".join(f"{i}. {s}" for i, s in enumerate(d["steps"], 1)) + "\n",
           "_Produces: " + "; ".join(d["produces"]).rstrip(".") + "._\n",
           authored("../SPECIALIZE.md", "postamble")]
    return "\n".join(out) + accounted_by("../SPECIALIZE.md")


def form(name):
    """The fenced block of a form in `.meta/templates/`, which is the form itself.

    The prose around it explains the form to whoever fills it in; the fence is
    what GitHub hands them. One copy, and this is the generator reading it —
    Literate Programming's rule applied to a template rather than to a schema.
    """
    text = (META / "templates" / name).read_text()
    fence = text.split("```markdown\n", 1)[1].split("\n```", 1)[0]
    return fence.rstrip("\n") + "\n"


def pull_request_template():
    """Renders the GitHub pull request markdown template form."""
    return form("pull-request.md")


def issue_template():
    """Renders the GitHub issue markdown template form."""
    return form("issue.md")


def roadmap_template():
    """Renders the GitHub roadmap item markdown template form."""
    return form("roadmap.md")


def _decision_slots():
    """The slot descriptions from the model, which is where the guidance lives.

    Read as plain YAML rather than through a SchemaView so the renderer keeps its
    one dependency, and from every module the class draws slots from — `falsifier`
    is `core`'s, shared with `Article`. The form and the record are two views of the same class, and
    a form whose headings were typed by hand would be the third copy of a shape
    the schema already states.
    """
    slots = {}
    for module in ("work/core.yaml", "work/decisions.yaml"):
        slots.update((load(module) or {}).get("slots") or {})
    return slots


def landed(number):
    """What a Challenge got, rendered from the entries taken under it.

    The account of a finished piece of work is not new prose: every line of it is
    already a `consequence` on some Decision, and writing it again by hand is the
    copy that flatters. So it is generated, and it is **exactly as complete as the
    record** — a decision taken under another change's coat-tails is missing here,
    which is the point rather than a defect.

    Prints rather than writes. It is addressed to a pull request at merge, so it
    goes through the channel that signs: `.meta/say/post landed 15` runs this for
    every Challenge the body closes and posts each. By hand:

        uvx --with pyyaml python .meta/render.py --landed 11
    """
    challenges = {c["id"]: c for path in
                  sorted((META / "assertions" / "challenges").glob("*.yaml"))
                  for c in (yaml.safe_load(path.read_text()) or {}).get("challenges") or []}
    ident = f"work:challenge/{number}"
    if ident not in challenges:
        return f"No Challenge {ident} is asserted."
    ch = challenges[ident]
    rows = [d for d in record() if d.get("challenge") == ident]
    out = [f"## What landed for #{number} — {ch['name']}\n"]
    if not rows:
        out.append("No decision names this Challenge.\n")
        return "\n".join(out)
    out.append(f"{len(rows)} decisions, and what each of them changed. Generated from the\n"
               f"record: an entry missing here was taken without one.\n")
    for d in rows:
        num = d["id"].rsplit("/", 1)[-1]
        head = f"**[DR-{num}]({RECORD.format(num)}) · {d['name'].split(' · ', 1)[-1]}**"
        if d.get("status") != "ADOPTED":
            head += f" — {d['status'].lower()}"
        out.append(head + "\n")
        out += [f"- {c.strip()}" for c in (d.get("consequences") or
                                           ["No consequences recorded."])]
        out.append("")
    return "\n".join(out)


def decisions():
    """The index to the record, and the only thing rendered from it (solorepo's DR-082).

    An entry is its assertion file, so rendering one as markdown made a second
    copy and nothing else. What survives is what a directory listing cannot do:
    map a number to the question it settled, so a reader can choose an entry
    without opening any, and invert `enacted_in` into the **By artifact** table,
    which is the only answer to "which decisions account for this file".

    Deliberately insufficient to apply anything, per Progressive Disclosure. A
    withdrawn entry is listed under Holes rather than in the record, and keeps
    its number, because a citation to a hole must still resolve.
    """
    rows = record()
    if not rows:
        return None
    structure = load("assertions/structure.yaml") or {}
    levels = {u["id"]: u["name"] for key in ("products", "projects")
              for u in structure.get(key) or []}
    out = [BANNER.format(src="assertions/decisions/"),
           authored("decisions.md"),
           "| Entry | The question it settled | Status |",
           "| :-- | :-- | :-- |"]
    paths = artifacts()
    holes = []
    for d in rows:
        num = d["id"].rsplit("/", 1)[-1]
        if d.get("status") == "WITHDRAWN":
            holes.append(d)
            continue
        status = (d.get("status") or "").capitalize()
        if d.get("status") == "SUPERSEDED":
            status = f"Superseded by {_link(rows, d['superseded_by'])}"
        title = d["name"].split(" · ", 1)[-1]
        # The level, where it is not the Portfolio's (solorepo's DR-093).
        for level in ("product", "project"):
            if d.get(level):
                title += f" · {levels.get(d[level], d[level])}"
        out.append(f"| [DR-{num}]({ENTRY.format(num)}) | {title} | {status} |")
    out.append("")
    if holes:
        out.append("## Holes\n")
        out.append("Numbers that were issued and are not decisions. They are never reused, and\n"
                   "the prose is kept: a paragraph that was worth writing does not stop being\n"
                   "true because it turned out to foreclose nothing.\n")
        for d in holes:
            num = d["id"].rsplit("/", 1)[-1]
            why = " ".join(d["withdrawn_because"].strip().split())
            out.append(f"- [DR-{num}]({ENTRY.format(num)}) — withdrawn. "
                       + why.split(". ")[0].rstrip(".") + ".")
        out.append("")
    by_artifact = {}
    for d in rows:
        for ref in (d.get("enacted_in") or []):
            by_artifact.setdefault(paths.get(ref, ref), []).append(
                d["id"].rsplit("/", 1)[-1])
    if by_artifact:
        out.append("## By artifact\n")
        out.append("Which entries account for a file. The other direction of `enacted_in`,\n"
                   "and the query a reader in a file actually has.\n")
        out.append("| Artifact | Entries |")
        out.append("| :-- | :-- |")
        for path in sorted(by_artifact):
            nums = ", ".join(f"[DR-{n}]({ENTRY.format(n)})"
                             for n in sorted(by_artifact[path]))
            out.append(f"| [`{path}`]({posixpath.relpath(path, '.meta')}) | {nums} |")
        out.append("")
    return "\n".join(out)


def _link(rows, ident):
    """A supersession, rendered as a link to the entry it names."""
    for d in rows:
        if d["id"] == ident:
            return f"[{d['name'].split(' · ')[0]}]({ENTRY.format(d['id'].rsplit('/', 1)[-1])})"
    return ident


def decision_form():
    """The form for an entry, rendered from the same class the record uses.

    One class at three levels — the Portfolio's, a Product's, a Project's —
    told apart by what the entry names (solorepo's DR-059, DR-093), so the form's headings
    are the model's slots and its guidance is their descriptions. Typing them
    here as well would be the copy that disagrees — and the copy that keeps a
    form asking for something the model stopped requiring.

    The chosen alternative asks for `reason` like the rejected one, because
    `reason`'s own description already says the chosen one's includes what it
    costs. It read `<As above, including what it costs.>` while that sentence
    sat in the model as well, which is the pair that drifts (solorepo's DR-152).
    What is left is woven: two blocks asserted on this page's Artifact, because
    no slot backs them.
    """
    slots = _decision_slots()
    if not slots:
        return None

    def guidance(name):
        return " ".join(slots[name]["description"].split())

    out = [BANNER.format(src="work/decisions.yaml"),
           authored("templates/decision.md"),
           "- **Status:** <" + " | ".join(
               (load("work/decisions.yaml") or {})["enums"]["DecisionStatus"]["permissible_values"]) + ">",
           "- **Level:** <Portfolio | Product: which | Project: which>\n",
           "## Context\n", "<" + guidance("context") + ">\n",
           "## Decision\n",
           "<" + woven("templates/decision.md", "decision") + ">\n",
           "## Alternatives considered\n",
           "<" + guidance("alternatives") + ">\n",
           "### A: <alternative> — rejected\n", "<" + guidance("reason") + ">\n",
           "### B: <alternative> — chosen\n", "<" + guidance("reason") + ">\n",
           "## Consequences\n", "<" + guidance("consequences") + ">\n",
           "## What would falsify this\n", "<" + guidance("falsifier") + ">\n",
           "## Bearing on the Charter\n",
           woven("templates/decision.md", "bearing on the charter") + "\n",
           "- **Applies:** <" + guidance("applies") + ">",
           "- **Departs from:** <" + guidance("departs_from") + ">\n",
           "## Supersedes\n",
           "<" + guidance("supersedes") + " Omit the section if there is none.>\n",
           "## Withdrawn because\n",
           "<" + guidance("withdrawn_because") + " Omit the section if there is none.>\n",
           "## Rationale\n", "<" + guidance("rationale") + ">\n"]
    return "\n".join(out)


def _discipline(name):
    for rel in ("assertions/disciplines.yaml", "assertions/imported/disciplines.yaml"):
        for d in (load(rel) or {}).get("disciplines") or []:
            if d["name"] == name:
                return d
    return None


def channel():
    """The channel's verbs, once: `.meta/say/verbs.yaml`."""
    return load("say/verbs.yaml")


def verb_line(program, verb, role=None):
    """How a verb is typed, from the table: the program, `--role` for any Role
    but the channel's default, the verb unless the program is the verb, and
    the shape of its arguments."""
    words = [f".meta/say/{program['name']}"]
    if role and role != "coder":
        words.append(f"--role {role}")
    if verb["name"] != program["name"]:
        words.append(verb["name"])
    if verb.get("usage"):
        words.append(verb["usage"])
    return " ".join(words)


def skill(name, discipline, target, commands, forms=(), role=None):
    """A Discipline, compiled for this harness, and for one Role (solorepo's DR-117).

    A skill is a Discipline plus the commands that carry it out, in the shape one
    harness loads on demand. Everything here is read from the assertions — the
    steps, the judgement, the Articles that enforce it, and any form's own fence.
    Nothing is restated, because a skill that restated the Discipline would be
    the copy nothing checks, and the one an agent actually reads.

    With a Role, the mechanical steps are one line and the Role's verbs, read
    from `verbs.yaml`: the verbs are the steps, each refuses its own misuse,
    and a reading names no verb its Role does not hold. The steps the assertion
    keeps are the ones no verb enforces. Without a Role the reading is the
    whole Discipline's, which is `disciplines.md`'s.

    The paragraphs between those parts are the Discipline's `woven` blocks and
    not this function's (solorepo's DR-152). They hang off the Discipline rather
    than off either page, because one Discipline compiles into a reading per
    Role: asserted on the Artifact each is written to, every one of them would
    be a copy of the last. `{role}` is the only thing a reading adds to one.

    Only the Claude Code target is emitted. The frontmatter an APM primitive
    wants is still unverified (solorepo's DR-040), and writing plausible field names would
    be worse than the gap; this is the same compilation at the scale that can be
    tested today.
    """
    d = _discipline(discipline)
    if d is None:
        return None
    articles = [a for a in ((load("assertions/imported/charter.yaml") or {}).get("articles") or [])
                if a.get("enforces") == d["id"]]
    out = ["---", f"name: {name}", "description: >-"]
    out += ["  " + line for line in textwrap.wrap(authored(target, "description"), 76)]
    out += ["---\n",
            "<!-- Generated by .meta/render.py from assertions/imported/disciplines.yaml.",
            "     Do not edit by hand: edit the assertion and re-render. -->\n",
            f"# {d['name']}\n",
            d["description"].strip() + "\n",
            "## Steps\n"]
    if role:
        table = channel() or {"programs": []}
        out += [woven(d, "verbs", role=role) + "\n"]
        for program in table["programs"]:
            held = [v for v in program["verbs"] if role in v["held_by"]]
            out += [f"- `{verb_line(program, v, role)}` — {v['does']}" for v in held]
        out += ["", woven(d, "steps") + "\n"]
    out += ["\n".join(f"{i}. {s.strip()}" for i, s in enumerate(d["steps"], 1)) + "\n",
            "## Where the judgement is\n",
            d["judgement"].strip() + "\n",
            woven(d, "commands") + "\n",
            "## Commands\n", "```bash", *commands, "```\n"]
    for title, form_name, block in forms:
        out += [f"## {title}\n", woven(d, block) + "\n", "```markdown",
                form(form_name).rstrip("\n"), "```\n"]
    if articles:
        out.append("## What is checked\n")
        for a in articles:
            out.append(f"- **A{a['id'].rsplit('/', 1)[-1]}.** {a['statement'].strip()}")
        out.append("")
    return "\n".join(out)


READING = ["python3 .meta/check_pr.py --sweep          # what this branch owns, and what it owes",
           "python3 .meta/check_pr.py <n> --threads    # the threads: owed, held, answered; and each verdict with its head",
           "python3 .meta/check_pr.py <n>              # the gate: A15 and A16",
           "#   Watching the pull request, and removing what a merge leaves behind, are the",
           "#   harness's business, not yours: AGENTS.md says how this one does both."]

# The coder's alone, and only in the coder's reading of the Discipline: the
# reading of a citation is run by whoever wrote it, before the hand-off, and a
# reviewer who reaches for it is doing the work over (solorepo's DR-134).
DEREFERENCE = [
    "just dereference                          # the citations this branch wrote, read against what they name",
    "#   Not a gate: its `x` is a finding to answer, and it blocks no merge."]

# The heading, the form's own file, and the name of the Discipline's `woven`
# block that introduces it. Naming a block is plumbing; writing one is not.
BODY = [("The body", "pull-request.md", "the body")]


def pr_first_skill():
    """The coder's reading. `/pr-first` and not `/pr-first-coder`, because the
    coder is the channel's default Role too: a session that names no Role is
    the coder's, in what it types and in what it reads (solorepo's DR-117)."""
    return skill(
        "pr-first", "PR First",
        "../.claude/skills/pr-first/SKILL.md",
        READING + DEREFERENCE, BODY, role="coder")


def pr_first_reviewer_skill():
    """The reviewer's reading: its verbs, the form a pull request is held to,
    and the judgement a reviewer's point is owed (solorepo's DR-117)."""
    return skill(
        "pr-first-reviewer", "PR First",
        "../.claude/skills/pr-first-reviewer/SKILL.md",
        READING, BODY, role="reviewer")


def wikisplain_skill():
    """Operational authoring skill for Knowledge Management wiki concepts (solorepo's DR-187)."""
    desc = authored("../.claude/skills/wikisplain/SKILL.md", "description").strip()
    return "\n".join([
        "---",
        "name: wikisplain",
        "description: >-",
        *["  " + line for line in textwrap.wrap(desc, 76)],
        "---",
        "",
        "<!-- Generated by .meta/render.py from assertions/structure.yaml.",
        "     Do not edit by hand: edit the assertion and re-render. -->",
        "",
        "# /wikisplain",
        "",
        "The `/wikisplain` skill creates, explains, and verifies encyclopedic wiki pages in `wiki/<context>/` following the [[knowledge-management|Knowledge Management]] discipline and Wikipedia editorial conventions (solorepo's DR-187).",
        "",
        "## When to Use",
        "",
        "- Minting a new concept in the Ubiquitous Language that requires maintainer-facing exposition.",
        "- Explaining an architectural subsystem, component, or domain concept for new maintainers.",
        "- Scaffolding a canonical wiki page with compliant MOS:LEAD phrasing, frontmatter, and closed-world wikilinks.",
        "- Checking for semantic duplicates or collisions against existing vocabulary and wiki pages.",
        "",
        "## Verbs",
        "",
        "- `just wikisplain <concept> [--context <context>] [--definition <def>] [--synonyms <s1,s2>]` — scaffold a wiki page and verify compliance",
        "- `python3 .meta/wikisplain.py <concept> --dry-run` — preview page content without writing to disk",
        "- `python3 .meta/wikisplain.py <concept> --check-duplicate` — check if a concept or slug already exists",
        "",
        "## Instructions",
        "",
        "1. **Check for Duplicates:** Run `python3 .meta/wikisplain.py \"<Concept>\" --check-duplicate` to verify no collision exists in vocabulary or existing wiki files.",
        "2. **Scaffold the Page:** Run `just wikisplain \"<Concept>\" --context <context> --definition \"<copular definition>\"` to generate the canonical structure.",
        "3. **Write Exposition:** Expand the page with narrative context, invariants, and relationships to other disciplines.",
        "4. **Wikilink Entities:** Use closed-world wikilinks (`[[concept]]` or scoped `[[context/concept]]`) to link related terms.",
        "5. **Verify Compliance:** Run `just gate meta` to ensure `wikilinks` and `wiki lead paragraphs` pass cleanly.",
        "",
        "## Invariants",
        "",
        "- **MOS:LEAD:** The first paragraph must open with `**<Concept>** is ...` matching the `# <Concept>` heading exactly.",
        "- **Closed-World Links:** Wikilinks `[[concept]]` must resolve to an existing wiki page or minted concept.",
        "- **Bounded Context:** Pages must reside in `wiki/<context>/` corresponding to their Bounded Context.",
        "",
    ])


def technical_writing_skill():
    """Technical writing skill fusing Diátaxis, Google style, and Literate Programming (solorepo's DR-171, solorepo's DR-175, solorepo's DR-176, solorepo's DR-187, solorepo's DR-194, solorepo's DR-196)."""
    desc = authored("../.claude/skills/technical-writing/SKILL.md", "description").strip()
    return "\n".join([
        "---",
        "name: technical-writing",
        "description: >-",
        *["  " + line for line in textwrap.wrap(desc, 76)],
        "---",
        "",
        "<!-- Generated by .meta/render.py from assertions/imported/structure.yaml.",
        "     Do not edit by hand: edit the assertion and re-render. -->",
        "",
        "# /technical-writing",
        "",
        "The `/technical-writing` skill operationalizes the character of `work:role/technical-writer` (`work:personality/technical-writer`) and enacts solorepo's DR-194, solorepo's DR-196, and solorepo's DR-198.",
        "",
        "## Two Communication and Authoring Regimes (solorepo's DR-198)",
        "",
        "1. **Conversational Communication Register:** In dialogue, PR review threads, turn responses, and issue comments, speak in the Technical Writer register (`work:personality/technical-writer`): *Spelled out, for an audience it names. Every citation dereferenced. Assume a reader who was not in the conversation, holds none of its shorthand, and arrives by search some years later. Length is not the cost here; ambiguity is.* This breaks the failure mode of abstruse, cryptic shorthand.",
        "2. **Durable Artifact Authoring Regime:** When authoring or editing durable files in the repository (code docstrings, Decision Records, wiki pages, companion logs), the structure, tone, and density are governed by the **Diátaxis quadrant** being authored. Conversational expansiveness must not be imported into item docstrings: Reference docstrings must remain dry, crisp, and contract-focused, with zero reviewer litigation.",
        "",
        "This standard combines Diátaxis documentation architecture, Google developer style sentences, and solorepo's Literate Programming (solorepo's DR-171, solorepo's DR-175, solorepo's DR-176) and Knowledge Management (solorepo's DR-184, solorepo's DR-185, solorepo's DR-187, solorepo's DR-196) disciplines.",
        "",
        "## Five Overarching Invariants",
        "",
        "1. **Every citation dereferenced (solorepo's DR-134, solorepo's DR-192):** Never leave a bare or unverified claim. A statement attributing a rule or behavior must cite its authority (`solorepo's DR-nnn`, `Article n`, `[[concept]]`). Check source assertions directly or search with `just search <query>` (solorepo's DR-103).",
        "2. **Use the Ubiquitous Language (solorepo's DR-190):** The codebase and LinkML ontologies are the word list. Write `Actor` (not user/bot), `Challenge` (not ticket/issue/story), `Role`, `Remit`, `Persona`.",
        "3. **The Reader's Test (solorepo's DR-175):** Can a reader use this item from its docstring alone without reading commit histories or PR threads?",
        "4. **No Reviewer Litigation in Code (solorepo's DR-171):** Docstrings state usage contracts, parameters, and invariants. They do not argue against past reviewers. The 'why' and trade-offs belong in Decision Records (`DR-nnn.yaml`) or module docstrings. Incident narratives belong in `<module>.history.md`.",
        "5. **The Residue Principle (solorepo's Article 15, solorepo's DR-196):** Pull request descriptions, issue comments, and commit messages are not documentation containers. What fits into any of the four Diátaxis quadrants belongs in a durable repository artifact. What remains is residue, and only residue belongs in a pull request body.",
        "",
        "## The Diátaxis Compass",
        "",
        "Select exactly one mode before writing:",
        "",
        "| Mode | Purpose | In Solorepo | Tone & Rules |",
        "|---|---|---|---|",
        "| **Reference** | Facts for lookup (Understanding + Work) | Public function, class, and method docstrings, LinkML schemas | Dry, complete, sure. Describe parameters, invariants, exceptions. No opinions, no tutorials, no past debate. |",
        "| **Explanation** | Understanding & why (Understanding + Learning) | Decision Records (`DR-nnn.yaml`), module overviews, wiki pages | Anchor on a real 'why' question. Context, constraints, alternatives, trade-offs. |",
        "| **How-To** | Steps to a goal (Action + Work) | `just` recipes, `SPECIALIZE.md`, workflow guides | Task-oriented, assume competence, action only. No digressions. 'Do X to achieve Y.' |",
        "| **Tutorial** | Learning by doing (Action + Learning) | Quickstarts, onboarding lessons | Guided, step-by-step, visible results at each step. |",
        "",
        "## Pre-Writing Routing: Where to Write",
        "",
        "Before typing prose for a change, execute this routing tree to select the container:",
        "",
        "1. **Task, recipe, or repeatable procedure:** `justfile` recipe or solorepo's `SPECIALIZE.md` (**How-To**).",
        "2. **Public function, class, schema, or API fact:** item docstring or LinkML schema (**Reference**, solorepo's DR-171, solorepo's DR-175).",
        "3. **Settled architectural choice between alternatives:** Decision Record in `.meta/assertions/decisions/DR-nnn.yaml` (**Explanation**).",
        "4. **Bug, incident, or regression history:** `<module>.history.md` with receipts (**Explanation**).",
        "5. **Enduring domain concept or subsystem overview:** `wiki/<context>/<concept>.md` via `just wikisplain` (**Explanation**, solorepo's DR-184, solorepo's DR-190).",
        "6. **Unrouted residue:** Pull request descriptions hold only transient reviewer handoff notes and links to surviving review threads or promoted Issues (solorepo's Article 15). Never summarize diffs.",
        "",
        "## Container Subordination",
        "",
        "The atomic semantic unit of domain knowledge is the Concept (solorepo's DR-195). Subordinate storage placement to the reader's posture:",
        "- **Schema Gloss:** `vocabulary.yaml` when machine checks and search aliases suffice.",
        "- **Section / Subsection:** `##` or `###` within an existing document when tightly bound to an aggregate.",
        "- **Dedicated Wiki Page:** `wiki/<context>/<concept>.md` when the concept has independent depth, invariants, or broad relevance.",
        "- **Subdirectory:** A folder grouping related concept pages for complex domain aggregates.",
        "",
        "Strictly avoid 'wiki article' (`avoid: [wiki article]`) to protect Charter Articles (solorepo's Article 1, solorepo's Article 15).",
        "",
        "## Google Developer Style Sentences",
        "",
        "- **Address the reader directly:** Use 'you' in the present tense. Reserve 'will' for things that genuinely occur later.",
        "- **Active voice:** 'The gate checks', not 'is checked by the gate'.",
        "- **Cut dead words:** 'To', not 'in order to'. 'Use', not 'utilize'. 'Do', not 'perform'.",
        "- **Specific over sterile:** Name the exact symbol, file, flag, or command name (`python3 .meta/search.py`, not 'the search script').",
        "- **Vary rhythm:** Mix sentence lengths on purpose. Short sentences land a point. Longer ones carry a fact with its condition or consequence.",
        "",
    ])


def justfile():
    """The root's verb surface, rendered so that the one line in it that names
    anything comes from the assertions rather than a list kept beside them
    (solorepo's DR-106).

    Every recipe invokes a tool under `.meta/` and implements nothing; `just
    --list` is the index. The doc comment on `gate` names what the runner
    takes, read from the Projects and Products asserted, which is the line
    that would otherwise drift when a Project is added. Never copied into a
    seed: a verb in every Project is what solorepo's DR-092 rejected.
    """
    structure = load("assertions/structure.yaml") or {}

    def tail(p):
        return p["id"].rsplit("/", 1)[-1]

    projects = ", ".join(tail(p) for p in structure.get("projects") or [])
    products = ", ".join(tail(p) for p in structure.get("products") or [])
    takes = (f"one Project: {projects}" if projects else "no Project is asserted yet")
    if products:
        takes += f" — or one Product: {products}"
    lines = [
        "# Generated by .meta/render.py from assertions/structure.yaml. Do not edit by hand:",
        "# edit the assertions and re-render.",
        "#",
        "# The verbs, typed. Every recipe invokes a tool under .meta/ and implements",
        "# nothing; `just --list` is the index (solorepo's DR-106). Not installed? `uvx --from rust-just just`.",
        "",
        "# every recipe, and what it does",
        "default:",
        "    @just --list --unsorted",
        "",
        f"# every Project's gate — or {takes}",
        'gate target="":',
        "    .meta/gate {{target}}",
        "",
        "# every generated page, from the assertions",
        "render:",
        "    uvx --with pyyaml python .meta/render.py",
        "",
        "# the pull request gate: A15, A16, A18, A19",
        "pr n:",
        "    python3 .meta/check_pr.py {{n}}",
        "",
        "# the subscription: one line per change, exiting on actionable events or when it closes",
        "watch n:",
        "    python3 .meta/check_pr.py {{n}} --watch",
        "",
        "# what this branch owns, and what it still owes",
        "sweep:",
        "    python3 .meta/check_pr.py --sweep",
        "",
        "# evaluate open pull requests and merge the top candidate in order of leverage",
        "merge-manager *args:",
        "    .meta/say/move merge-manager {{args}}",
        "",
        "# what landed for a Challenge, from the record; `.meta/say/post landed <pr>` posts it",
        "landed n:",
        "    uvx --with pyyaml python .meta/render.py --landed {{n}}",
        "",
        "# what to work on next: pull requests, loops, the milestone, and what is ripe",
        "next:",
        "    python3 .meta/next.py",
        "",
        "# what the workflows cost in time: waiting for a runner, and running",
        "timing *args:",
        "    python3 .meta/timing.py {{args}}",
        "",
        "# count review subagent invocations against the fan-out ceiling (solorepo's DR-191)",
        "agents *args:",
        "    python3 .meta/agents.py {{args}}",
        "",
        "# explain or scaffold a wiki concept following Knowledge Management conventions (solorepo's DR-187)",
        "wikisplain *args:",
        "    python3 .meta/wikisplain.py {{args}}",
        "",
        "# the citations this branch wrote, read against what they name; not a gate",
        'dereference *args:',
        "    uvx --with linkml --with pyyaml python .meta/dereference.py {{args}}",
        "",
        "# search assertions, decisions, and wiki by meaning (solorepo's DR-103)",
        'search *args:',
        "    uvx --with linkml --with pyyaml python .meta/search.py {{args}}",
    ]

    artifacts = {art["id"] for art in structure.get("artifacts") or [] if "id" in art}

    if "work:artifact/meta-arc-cluster" in artifacts:
        lines += [
            "",
            "# the optional local cluster this repo's self-hosted runner can use",
            "arc-cluster:",
            "    .meta/arc/cluster",
        ]

    if "work:artifact/meta-arc-deploy" in artifacts:
        lines += [
            "",
            "# deploy or update the self-hosted runner (ARC) this repo's CI uses,",
            "# against whatever cluster kubectl is currently pointed at",
            "arc:",
            "    .meta/arc/deploy",
        ]

    return "\n".join(lines) + "\n"


def gitattributes():
    """`merge=union` for every path this file writes, from the list that writes them.

    A generated page carries no information its sources do not, and the gate
    byte-compares each one against a fresh render, so the committed copy is
    already pinned to the assertions. That makes a merge conflict in one of
    them a conflict about nothing: whatever git settles on is overwritten by
    the next `just render`, and the gate is red until it is.

    They conflict anyway, and for a reason that will not stop: two branches
    that each record a decision both append a row after the last one in
    `decisions.md`, which is one insertion point and two additions. Minting
    stopped them taking the same number (solorepo's DR-128); it does not stop
    them writing to the same line of the file rendered from the numbers.

    `union` takes both sides rather than asking, and `just render` then puts
    the result in the order the sources give. Where both sides changed one row
    — two entries citing one artifact — union leaves both copies, the gate
    says `rendered prose` and the re-render corrects it. Wrong output that the
    gate already catches, in place of a stop that a human has to clear.

    It is local only: GitHub does not read a repository's `.gitattributes`
    when it merges, so the pull request still reads `CONFLICTING` until the
    rebase is pushed. What this removes is the hand-editing inside that
    rebase, not the label in front of it.

    The list is `TARGETS` itself, so a page added there is covered by the act
    of adding it. Every pattern is anchored with a leading `/`: a pattern with
    no slash in it matches a basename at any depth, so a bare `justfile` would
    union a nested one that no gate byte-compares (solorepo's #194).
    """
    names = {"../.gitattributes"}
    for name, fn in TARGETS.items():
        if fn is gitattributes:
            continue
        result = fn()
        if result is None:
            continue
        names.update(result if isinstance(result, dict) else {name: None})
    paths = sorted(f"/{name.removeprefix('../')}" if name.startswith("../")
                   else f"/.meta/{name}" for name in names)
    return "\n".join([
        "# Generated by .meta/render.py from the list of pages it renders.",
        "# Do not edit by hand: add the page to TARGETS and re-render.",
        "#",
        "# A generated page is pinned to its sources by the gate, so a conflict in",
        "# one is a conflict about nothing. `union` keeps both sides and the next",
        "# `just render` puts them in order (solorepo's DR-143). GitHub ignores",
        "# this file when it merges; it is the rebase here that it spares.",
        "",
    ] + [f"{path} merge=union" for path in paths]) + "\n"


TARGETS = {"disciplines.md": disciplines,
           "decisions.md": decisions,
           "templates/decision.md": decision_form,
           "charter.md": charter,
           "vocabulary.md": vocabulary,
           "../SPECIALIZE.md": specialize,
           "../justfile": justfile,
           "../.github/PULL_REQUEST_TEMPLATE.md": pull_request_template,
           "../.github/ISSUE_TEMPLATE/challenge.md": issue_template,
           "../.github/ISSUE_TEMPLATE/roadmap.md": roadmap_template,
           "../.claude/skills/pr-first/SKILL.md": pr_first_skill,
           "../.claude/skills/pr-first-reviewer/SKILL.md": pr_first_reviewer_skill,
           "../.claude/skills/wikisplain/SKILL.md": wikisplain_skill,
           "../.claude/skills/technical-writing/SKILL.md": technical_writing_skill,
           "../.gitattributes": gitattributes}

def rendered():
    """Every generated path, relative to `.meta/`, mapped to its content.

    A target renders one file or a set of them. Both callers — the writer below
    and `check.py`'s staleness check — want the flat mapping, so the fan-out is
    resolved once here rather than in each of them.

    Counts are filled last, over every page alike: a sentence citing one is
    prose in the assertions, and which generator carries it to a page is not
    that sentence's business.
    """
    out = {}
    for name, fn in TARGETS.items():
        result = fn()
        if result is None:
            continue
        out.update(result if isinstance(result, dict) else {name: result})
    return {name: counted(text) for name, text in out.items()}


def unrendered():
    """Targets that produce nothing and yet have a file on disk, by name.

    By name and not as a sentence about the name, because both callers key on
    the page: the gate wraps it in prose, and `check_pr.py` asks whether the
    record's index is one of them. A sentence answered that question `False`
    however the page stood.
    """
    return [name for name, fn in TARGETS.items()
            if fn() is None and (META / name).exists()]


if __name__ == "__main__":
    if "--landed" in sys.argv:
        print(landed(sys.argv[sys.argv.index("--landed") + 1]))
        sys.exit(0)
    check = "--check" in sys.argv
    pages = rendered()
    orphans = unrendered()
    stale = []
    for name, text in pages.items():
        path, want = META / name, text.rstrip("\n") + "\n"
        if check:
            if not path.exists() or path.read_text() != want:
                stale.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(want)
    if check:
        # Two answers under two prefixes, because they are not the same answer
        # and neither is the other's repair. A stale page is made current by
        # running this program; a page nothing renders is not made anything by
        # it, and what is wrong is the target or the file. Printed on one line
        # under one word they were indistinguishable to a reader and to
        # `check_pr.py`, which named the second one's repair as the first's.
        if stale:
            print("stale: " + ", ".join(stale))
        if orphans:
            print("unrendered: " + ", ".join(orphans))
        if not (stale or orphans):
            print("up to date")
        sys.exit(1 if stale or orphans else 0)
    print(f"wrote {len(pages)} files")
