#!/usr/bin/env python3
"""Render the prose satellites from the assertions they describe.

`disciplines.md` and `vocabulary.md` list things that `.meta/assertions/` already
holds. Maintaining both by hand is the drift these Disciplines exist to prevent,
so the prose derives and the assertions are the source.

    uvx --with pyyaml python .meta/render.py           # write
    uvx --with pyyaml python .meta/render.py --check   # fail if stale

Definitions in the vocabulary are one-line glosses. The full reasoning stays on
the class, per Literate Programming; these are for recognising a term, not for
applying it.
"""
import sys, pathlib, yaml

META = pathlib.Path(__file__).parent
BANNER = ("<!-- Generated by .meta/render.py from {src}. Do not edit by hand:\n"
          "     edit the assertions and re-render. -->\n\n")


def load(rel):
    return yaml.safe_load((META / rel).read_text())


def disciplines():
    tbox = load("work/disciplines.yaml")
    abox = load("assertions/disciplines.yaml")
    out = [BANNER.format(src="assertions/disciplines.yaml"),
           "## Disciplines\n",
           "_Structured ways of working that must be adhered to._\n",
           tbox["description"].strip() + "\n"]
    for d in abox["disciplines"]:
        out.append(f"### {d['name']}\n")
        if d.get("description"):
            out.append(d["description"].strip() + "\n")
        if d.get("judgement"):
            out.append(f"**Where the judgement is.** {d['judgement'].strip()}\n")
        if d.get("steps"):
            out.append("\n".join(f"{i}. {s}" for i, s in enumerate(d["steps"], 1)) + "\n")
        if d.get("produces"):
            out.append("_Produces: " + "; ".join(d["produces"]).rstrip(".") + "._\n")
    return "\n".join(out)


def vocabulary():
    abox = load("assertions/vocabulary.yaml")
    schemes = {s["id"]: s for s in abox["concept_schemes"]}
    out = [BANNER.format(src="assertions/vocabulary.yaml"),
           "## Vocabulary\n",
           "_The words this repo uses, and what they mean._\n",
           "A Concept is a unit of meaning, not a word — which is why two entries\n"
           "below share a label. Use the preferred label; do not mint a term without\n"
           "the solo. Check DDD first, then this vocabulary, then ask.\n"]
    for sid, scheme in schemes.items():
        members = [c for c in abox["concept_set"] if c.get("in_scheme") == sid]
        if not members:
            continue
        out.append(f"### {scheme['name']}\n")
        out.append(f"_Authority: {scheme.get('authority', 'unstated')}._\n")
        out.append("| Term | Means | Do not say |\n|---|---|---|")
        for c in members:
            avoid = ", ".join(c.get("avoid", [])) or "—"
            out.append(f"| **{c['pref_label']}** | {c['definition'].strip()} | {avoid} |")
        out.append("")
        for c in members:
            if c.get("scope_note"):
                out.append(f"**{c['pref_label']}.** {c['scope_note'].strip()}\n")
    collisions = [c for c in abox["concept_set"] if c.get("confusable_with")]
    if collisions:
        by_label = {c["id"]: c["pref_label"] for c in abox["concept_set"]}
        out.append("### Confusables\n")
        out.append("One word, more than one meaning. The hazard a vocabulary "
                   "guards against is\nmore often a collision than a gap.\n")
        out.append("| This | Is not | \n|---|---|")
        for c in collisions:
            others = ", ".join(by_label.get(o, o) for o in c["confusable_with"])
            out.append(f"| **{c['pref_label']}** | {others} |")
        out.append("")
    return "\n".join(out)


TARGETS = {"disciplines.md": disciplines, "vocabulary.md": vocabulary}

if __name__ == "__main__":
    check = "--check" in sys.argv
    stale = []
    for name, fn in TARGETS.items():
        want, path = fn().rstrip("\n") + "\n", META / name
        if check:
            if not path.exists() or path.read_text() != want:
                stale.append(name)
        else:
            path.write_text(want)
            print(f"wrote {name}")
    if check:
        print("stale: " + ", ".join(stale) if stale else "up to date")
        sys.exit(1 if stale else 0)
