target-version = "py313"
line-length = 100

[lint]
select = [
    "E4",
    "E501",
    "E7",
    "E9",
    "W",
    "F",
    "I",
    "N",
    "UP",
    "B",
    "BLE",
    "C4",
    "C90",
    "DTZ",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLW1510",
    "RET",
    "SIM",
    "TRY003",
    "RUF",
    "PTH",
]
ignore = []

[lint.mccabe]
max-complexity = 12

[lint.pylint]
max-args = 5
max-branches = 12
max-statements = 50

[lint.isort]
known-first-party = ["checks", "check_pr", "channel", "lib", "depth"]
